DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0041"] = [
	{ "s": "A", "p": [10, 4, 7, 9, 6, 11, 5] },
	{ "s": "ABARCA", "p": [7] },
	{ "s": "ABRIRÁ", "p": [10] },
	{ "s": "ACCEDAN", "p": [10] },
	{ "s": "ACCEDER", "p": [10] },
	{ "s": "ACCESIBLE", "p": [6] },
	{ "s": "ACCESO", "p": [8, 4] },
	{ "s": "ACCESOS", "p": [6, 4, 8] },
	{ "s": "ACCIDENTAL", "p": [9, 5, 3] },
	{ "s": "ACCIONES", "p": [6, 5] },
	{ "s": "ACTIVADO", "p": [4] },
	{ "s": "ACTIVAR", "p": [6] },
	{ "s": "ACTIVAS", "p": [6] },
	{ "s": "ACTIVIDADES", "p": [6, 4] },
	{ "s": "ACTIVO", "p": [10, 8] },
	{ "s": "ACTIVOS", "p": [8, 3] },
	{ "s": "ACTUALIZADO", "p": [10, 6, 5] },
	{ "s": "ACTUALIZADOS", "p": [10] },
	{ "s": "ACTUALIZAN", "p": [11] },
	{ "s": "ACTUALIZAR", "p": [10, 6] },
	{ "s": "ACTUALIZARSE", "p": [10] },
	{ "s": "ACTÚA", "p": [11] },
	{ "s": "ACUERDO", "p": [4] },
	{ "s": "ADAPTARSE", "p": [11] },
	{ "s": "ADMIN", "p": [10, 6, 4] },
	{ "s": "ADMINISTRACIÓN", "p": [10] },
	{ "s": "ADMINISTRADAS", "p": [7] },
	{ "s": "ADMINISTRADOR", "p": [9, 8, 6, 4] },
	{ "s": "ADMINISTRADOS", "p": [4] },
	{ "s": "ADVIERTEN", "p": [4] },
	{ "s": "AFECTA", "p": [8] },
	{ "s": "AFECTACIONES", "p": [5] },
	{ "s": "AFECTACIÓN", "p": [10] },
	{ "s": "AFECTADA", "p": [10] },
	{ "s": "AFECTADAS", "p": [6] },
	{ "s": "AFECTADO", "p": [7, 6] },
	{ "s": "AFECTADOS", "p": [5] },
	{ "s": "AFECTAR", "p": [11] },
	{ "s": "AFECTE", "p": [7] },
	{ "s": "AFECTEN", "p": [4] },
	{ "s": "AHÍ", "p": [10] },
	{ "s": "AJUSTES", "p": [7] },
	{ "s": "AL", "p": [10, 9, 7, 8] },
	{ "s": "ALCANCE", "p": [5, 3] },
	{ "s": "ALERTAS", "p": [4] },
	{ "s": "ALIMENTANDO", "p": [11] },
	{ "s": "ALINEADAS", "p": [10, 7, 6] },
	{ "s": "ALLITEMS", "p": [10] },
	{ "s": "ALLÍ", "p": [10] },
	{ "s": "ALMACENADAS", "p": [5] },
	{ "s": "ALMACENAMIENTO", "p": [9] },
	{ "s": "ALMACENAN", "p": [4] },
	{ "s": "ALMACENARLAS", "p": [7] },
	{ "s": "ALOJADO", "p": [11, 10] },
	{ "s": "ALOJADOS", "p": [5] },
	{ "s": "ALTA", "p": [8] },
	{ "s": "ALTAMENTE", "p": [10] },
	{ "s": "ALTERNATIVO", "p": [10, 4] },
	{ "s": "ALTERNO", "p": [11, 10, 4] },
	{ "s": "AMBIENTE", "p": [9] },
	{ "s": "ANALISTA", "p": [7, 8, 6, 5, 4] },
	{ "s": "ANALISTAS", "p": [7] },
	{ "s": "AND", "p": [10] },
	{ "s": "ANTE", "p": [6, 11, 10, 9, 4] },
	{ "s": "ANTERIOR", "p": [9] },
	{ "s": "ANTERIORES", "p": [10, 7] },
	{ "s": "ANTES", "p": [7, 10] },
	{ "s": "ANUAL", "p": [11] },
	{ "s": "ANUALES", "p": [10] },
	{ "s": "ANÁLISIS", "p": [11] },
	{ "s": "ANÓMALO", "p": [4] },
	{ "s": "APLICA", "p": [6] },
	{ "s": "APLICACIONES", "p": [8, 5, 9, 7, 3] },
	{ "s": "APLICACIÓN", "p": [4] },
	{ "s": "APLICAMOS", "p": [10] },
	{ "s": "APLICAR", "p": [10] },
	{ "s": "APOYAR", "p": [4] },
	{ "s": "APOYÁNDONOS", "p": [4] },
	{ "s": "APPS", "p": [4, 6, 2, 5, 3, 8] },
	{ "s": "APRENDIDAS", "p": [11] },
	{ "s": "APRETAMOS", "p": [10] },
	{ "s": "APROXIMADAMENTE", "p": [10] },
	{ "s": "ARCHIVO", "p": [10, 9] },
	{ "s": "ARCHIVOS", "p": [9, 10] },
	{ "s": "ARQUITECTURA", "p": [6] },
	{ "s": "ASEGURANDO", "p": [6, 5] },
	{ "s": "ASEGURAR", "p": [10, 6] },
	{ "s": "ASEGURARSE", "p": [10] },
	{ "s": "ASIGNACIÓN", "p": [6, 3] },
	{ "s": "ASIGNADOS", "p": [9, 8] },
	{ "s": "ASOCIADO", "p": [8] },
	{ "s": "ASPX", "p": [10] },
	{ "s": "ASÍ", "p": [9, 6] },
	{ "s": "ATENCIÓN", "p": [4] },
	{ "s": "AUDITORÍA", "p": [6, 4] },
	{ "s": "AUDITORÍAS", "p": [11] },
	{ "s": "AUMENTAR", "p": [11] },
	{ "s": "AUTENTICACIÓN", "p": [6, 4] },
	{ "s": "AUTOMATE", "p": [6, 5, 8, 4, 3] },
	{ "s": "AUTOMATIZACIÓN", "p": [5] },
	{ "s": "AUTOMATIZADAS", "p": [4] },
	{ "s": "AUTOMATIZADO", "p": [9, 4] },
	{ "s": "AUTOMATIZADOS", "p": [5, 11, 10, 6] },
	{ "s": "AUTOMÁTICA", "p": [9] },
	{ "s": "AUTOMÁTICAS", "p": [6] },
	{ "s": "AUTOMÁTICOS", "p": [4] },
	{ "s": "AUTORIZADAS", "p": [4] },
	{ "s": "AUTORIZADOS", "p": [8, 6, 4] },
	{ "s": "AUTORIZAR", "p": [7] },
	{ "s": "AZURE", "p": [9, 3] }
];