DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0054"] = [
	{ "s": "TABLAS", "p": [5] },
	{ "s": "TAMBIÉN", "p": [7] },
	{ "s": "TANTO", "p": [5, 4] },
	{ "s": "TAREAS", "p": [6, 5] },
	{ "s": "TECNOLOGÍA", "p": [6, 4] },
	{ "s": "TECNOLÓGICA", "p": [6] },
	{ "s": "TECNOLÓGICOS", "p": [11, 4] },
	{ "s": "TENANT", "p": [10, 11, 4, 3] },
	{ "s": "TENEMOS", "p": [10] },
	{ "s": "TENER", "p": [10] },
	{ "s": "TI", "p": [9, 6] },
	{ "s": "TI/DESARROLLO", "p": [6] },
	{ "s": "TIEMPO", "p": [4, 11, 10, 9, 3] },
	{ "s": "TIEMPOS", "p": [10] },
	{ "s": "TIME", "p": [4] },
	{ "s": "TITLE", "p": [1] },
	{ "s": "TO", "p": [10] },
	{ "s": "TODA", "p": [7] },
	{ "s": "TODAS", "p": [7, 5] },
	{ "s": "TODO", "p": [10] },
	{ "s": "TODOS", "p": [8, 6, 5, 4] },
	{ "s": "TOTAL", "p": [10, 9, 8, 5] },
	{ "s": "TRACK", "p": [10] },
	{ "s": "TRANSACCIONALES", "p": [10] },
	{ "s": "TRAS", "p": [8, 6, 5, 4] },
	{ "s": "TRATA", "p": [10] },
	{ "s": "TRAZABILIDAD", "p": [11, 4] },
	{ "s": "TRES", "p": [10] },
	{ "s": "TRÁFICO", "p": [9] },
	{ "s": "TÉCNICAS", "p": [11, 7, 6, 4] },
	{ "s": "TÉCNICO", "p": [6] },
	{ "s": "TÉCNICOS", "p": [5, 4] }
];