DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex.prefixes = [
	{ "fileName": "0xu0031.js", "first": "1", "last": "120" },
	{ "fileName": "0xu0032.js", "first": "2", "last": "28" },
	{ "fileName": "0xu0033.js", "first": "3", "last": "3.2.5" },
	{ "fileName": "0xu0034.js", "first": "4", "last": "43" },
	{ "fileName": "0xu0035.js", "first": "5", "last": "5" },
	{ "fileName": "0xu0036.js", "first": "6", "last": "6.3" },
	{ "fileName": "0xu0037.js", "first": "7", "last": "7.7" },
	{ "fileName": "0xu0038.js", "first": "8", "last": "8" },
	{ "fileName": "0xu0039.js", "first": "9", "last": "99.9" },
	{ "fileName": "0xu0041.js", "first": "A", "last": "AZURE" },
	{ "fileName": "0xu0042.js", "first": "B", "last": "BÁSICA" },
	{ "fileName": "0xu0043.js", "first": "C", "last": "CUYA" },
	{ "fileName": "0xu0044.js", "first": "DAMOS", "last": "DÍAS" },
	{ "fileName": "0xu0045.js", "first": "E", "last": "EXTRAEN" },
	{ "fileName": "0xu0046.js", "first": "FACILITANDO", "last": "FUNDAMENTALES" },
	{ "fileName": "0xu0047.js", "first": "GARANTIZA", "last": "GUARDADOS" },
	{ "fileName": "0xu0048.js", "first": "HA", "last": "HUMANOS" },
	{ "fileName": "0xu0049.js", "first": "IDENTIFICA", "last": "IT" },
	{ "fileName": "0xu004a.js", "first": "JSON", "last": "JSON" },
	{ "fileName": "0xu004c.js", "first": "LA", "last": "LÓGICA" },
	{ "fileName": "0xu004d.js", "first": "MAGNITUD", "last": "MÓDULOS" },
	{ "fileName": "0xu004e.js", "first": "NATURALEZA", "last": "NUEVO" },
	{ "fileName": "0xu004f.js", "first": "O", "last": "OTRO" },
	{ "fileName": "0xu0050.js", "first": "PAGOS", "last": "PÉRDIDA" },
	{ "fileName": "0xu0051.js", "first": "QA", "last": "QUIEN" },
	{ "fileName": "0xu0052.js", "first": "RANGO", "last": "RTO" },
	{ "fileName": "0xu0053.js", "first": "SANDBOX", "last": "SUS" },
	{ "fileName": "0xu0054.js", "first": "TABLAS", "last": "TÉCNICOS" },
	{ "fileName": "0xu0055.js", "first": "UBICACIÓN", "last": "UTILIZAR" },
	{ "fileName": "0xu0056.js", "first": "VALIDACIONES", "last": "VOLUMINOSAS" },
	{ "fileName": "0xu0059.js", "first": "Y", "last": "Y" },
	{ "fileName": "0xu005a.js", "first": "ZIP", "last": "ZIP" },
	{ "fileName": "0xu00c1.js", "first": "ÁREA", "last": "ÁREA" },
	{ "fileName": "0xu00cd.js", "first": "ÍNDICE", "last": "ÍNDICE" },
	{ "fileName": "0xu00d3.js", "first": "ÓPTIMO", "last": "ÓPTIMO" },
	{ "fileName": "0xu00da.js", "first": "ÚNICAMENTE", "last": "ÚNICAMENTE" },
	{ "fileName": "0xu00dc.js", "first": "Ü", "last": "Ü" }
];