DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0044"] = [
	{ "s": "DATA", "p": [8] },
	{ "s": "DATAVERSE", "p": [4, 8, 3] },
	{ "s": "DATOS", "p": [4, 8, 3, 1] },
	{ "s": "DC_ADMINISTRACIONESADUANAS", "p": [5] },
	{ "s": "DC_ADUANA", "p": [6] },
	{ "s": "DC_ADUANAS", "p": [7, 6, 5] },
	{ "s": "DC_ADUANASID", "p": [6] },
	{ "s": "DC_AGENTE", "p": [7, 6] },
	{ "s": "DC_AGENTEADUANERO", "p": [7, 6] },
	{ "s": "DC_ASNG_CONTACTOS", "p": [5] },
	{ "s": "DC_ASOCIADODENEGOCIOS", "p": [7, 6, 5] },
	{ "s": "DC_ASOCIADODENEGOCIOSID", "p": [6] },
	{ "s": "DC_ASOCIADODENEGOCIOS_DC_LISTASDEPRECIO", "p": [5] },
	{ "s": "DC_AUDITORIA", "p": [5] },
	{ "s": "DC_AYUDA", "p": [5] },
	{ "s": "DC_BARCOSYAERONAVES", "p": [5] },
	{ "s": "DC_CARGARLISTADEPRECIO", "p": [7, 6] },
	{ "s": "DC_CARGOSCONSOLIDADO", "p": [5] },
	{ "s": "DC_CARGOSINDIVIDUALES", "p": [5] },
	{ "s": "DC_CERTIFICADOSYTRATADOS", "p": [5] },
	{ "s": "DC_CLIENTE", "p": [7, 6] },
	{ "s": "DC_CODIGOADUANA", "p": [5] },
	{ "s": "DC_CONDUCTOR", "p": [7, 6] },
	{ "s": "DC_CONFIGURACION", "p": [5] },
	{ "s": "DC_CONSIGNATARIO", "p": [7, 6] },
	{ "s": "DC_CONSOLIDADO", "p": [7, 6, 5] },
	{ "s": "DC_CONSOLIDADOID", "p": [6] },
	{ "s": "DC_CONTACTOS", "p": [5] },
	{ "s": "DC_CONTENEDOR", "p": [7, 6] },
	{ "s": "DC_CONTENEDORES", "p": [7, 6, 5] },
	{ "s": "DC_CONTENEDORESID", "p": [6] },
	{ "s": "DC_CONTENEDORES_DC_ADUANAS", "p": [5] },
	{ "s": "DC_CONTENEDORES_DC_EMBARQUES", "p": [5] },
	{ "s": "DC_CONTENEDORES_DC_TRANSPORTE", "p": [5] },
	{ "s": "DC_COTIZACION", "p": [7, 6, 5] },
	{ "s": "DC_COTIZACIONESNL", "p": [5] },
	{ "s": "DC_COTIZACIONID", "p": [6] },
	{ "s": "DC_CREDITOCOMPRAS", "p": [5] },
	{ "s": "DC_CUENTAPRINCIPAL", "p": [7, 6] },
	{ "s": "DC_DECLARACIONES", "p": [5] },
	{ "s": "DC_DEPOSITOLOGISTICO", "p": [7, 6] },
	{ "s": "DC_DEPOSITOSADUANALES", "p": [5] },
	{ "s": "DC_DESPACHOTRANSPORTE", "p": [7, 6, 5] },
	{ "s": "DC_DESPACHOTRANSPORTEID", "p": [6] },
	{ "s": "DC_DIFLOGS", "p": [5] },
	{ "s": "DC_DISTRIBUCIONCONTENEDORES", "p": [5] },
	{ "s": "DC_DOCUMENTOSASOCIADOSDENEGOCIOS", "p": [5] },
	{ "s": "DC_DOCUMENTOSOPERACIONES", "p": [5] },
	{ "s": "DC_DOCUMENTOSVEHICULOS", "p": [5] },
	{ "s": "DC_EMBARCADOR", "p": [7, 6] },
	{ "s": "DC_EMBARQUE", "p": [7, 6] },
	{ "s": "DC_EMBARQUES", "p": [7, 6, 5] },
	{ "s": "DC_EMBARQUESID", "p": [6] },
	{ "s": "DC_EXPEDIENTE", "p": [5] },
	{ "s": "DC_FACTURACOL", "p": [7, 6] },
	{ "s": "DC_FACTURANCF", "p": [7, 6] },
	{ "s": "DC_FACTURARA", "p": [7, 6] },
	{ "s": "DC_FACTURARADICIONAL", "p": [7, 6] },
	{ "s": "DC_FACTURAREEMBOLSO", "p": [7, 6] },
	{ "s": "DC_FACTURAS", "p": [7, 6, 5] },
	{ "s": "DC_FACTURASID", "p": [6] },
	{ "s": "DC_FILEBL", "p": [5] },
	{ "s": "DC_FILEBLBILLOFLADING", "p": [5] },
	{ "s": "DC_FILEBLCONTAINER", "p": [5] },
	{ "s": "DC_FILEBLSHAREPOINTS", "p": [5] },
	{ "s": "DC_HBL", "p": [7, 6] },
	{ "s": "DC_HBLASOCIADO", "p": [7, 6] },
	{ "s": "DC_HOMOLOGACIONPRODUCTOSLIQUIDACION", "p": [5] },
	{ "s": "DC_HOMOLOGACIONSIGA", "p": [5] },
	{ "s": "DC_INCIDENCIASADUANAS", "p": [5] },
	{ "s": "DC_INCIDENCIASEMBARQUES", "p": [5] },
	{ "s": "DC_INCIDENCIASTRANSPORTE", "p": [5] },
	{ "s": "DC_INCIDENCIASVEHICULOS", "p": [5] },
	{ "s": "DC_INCIDENCIASVENTAS", "p": [5] },
	{ "s": "DC_LIQUIDACIONDEEMBARQUE", "p": [5] },
	{ "s": "DC_LISTADEPRECIO", "p": [7, 6] },
	{ "s": "DC_LISTASDEPRECIOS", "p": [7, 6, 5] },
	{ "s": "DC_LISTASDEPRECIOSID", "p": [6] },
	{ "s": "DC_LISTASDEPRECIOS_DC_ASOCIADODENEGOCIO", "p": [5, 6] },
	{ "s": "DC_LISTASDEPRECIOS_DC_ASOCIADODENEGOCIOID", "p": [6] },
	{ "s": "DC_LOCALIDADESTRANSPORTE", "p": [5] },
	{ "s": "DC_LOGSDIFPRODUCTOS", "p": [5] },
	{ "s": "DC_LOGSOPERACIONES", "p": [5] },
	{ "s": "DC_LP_CARGOSCONSOLIDADOS", "p": [7, 6] },
	{ "s": "DC_LP_CARGOSDEPOSITOS", "p": [7, 6] },
	{ "s": "DC_LP_CARGOSINDIVIDUALES", "p": [7, 6] },
	{ "s": "DC_MAESTROCHASIS", "p": [5] },
	{ "s": "DC_MAESTROINCIDENCIASADUANAS", "p": [5] },
	{ "s": "DC_MAESTROINCIDENCIASEMBARQUES", "p": [5] },
	{ "s": "DC_MAESTROINCIDENCIASTRANSPORTE", "p": [5] },
	{ "s": "DC_MAESTROINCIDENCIASVEHICULOS", "p": [5] },
	{ "s": "DC_MAESTROINCIDENCIASVENTAS", "p": [5] },
	{ "s": "DC_MAESTROPRODUCTOS", "p": [5] },
	{ "s": "DC_MANTENIMIENTOVEHICULOS", "p": [5] },
	{ "s": "DC_MAWBMBL", "p": [7, 6] },
	{ "s": "DC_NIETOS", "p": [7, 6] },
	{ "s": "DC_NOTASDECREDITO", "p": [5] },
	{ "s": "DC_NOTIFICARA", "p": [7, 6] },
	{ "s": "DC_OPORTUNIDAD", "p": [5] },
	{ "s": "DC_ORDENESDECOMPRA", "p": [7, 6, 5] },
	{ "s": "DC_ORDENESDECOMPRAID", "p": [6] },
	{ "s": "DC_PAIS", "p": [5] },
	{ "s": "DC_PENALIDADCOMISIONES", "p": [5] },
	{ "s": "DC_PERFILCLIENTE", "p": [7, 6] },
	{ "s": "DC_PERFILESCLIENTE", "p": [7, 6, 5] },
	{ "s": "DC_PERFILESCLIENTEID", "p": [6] },
	{ "s": "DC_PESOVOLUMETRICO", "p": [5] },
	{ "s": "DC_PRODUCTOSADUANA", "p": [5] },
	{ "s": "DC_PRODUCTOSADUANASNC", "p": [5] },
	{ "s": "DC_PRODUCTOSCOLECTAR", "p": [5] },
	{ "s": "DC_PRODUCTOSCREDITOCOMPRAS", "p": [5] },
	{ "s": "DC_PRODUCTOSDECLARACIONES", "p": [5] },
	{ "s": "DC_PRODUCTOSDEEMBARQUE", "p": [5] },
	{ "s": "DC_PRODUCTOSDEPERFIL", "p": [5] },
	{ "s": "DC_PRODUCTOSDEPOSITOS", "p": [5] },
	{ "s": "DC_PRODUCTOSDEVENTAS", "p": [5] },
	{ "s": "DC_PRODUCTOSEMBARQUES", "p": [5] },
	{ "s": "DC_PRODUCTOSEMBARQUESNC", "p": [5] },
	{ "s": "DC_PRODUCTOSFACTURA", "p": [5] },
	{ "s": "DC_PRODUCTOSLISTADEPRECIOS", "p": [5] },
	{ "s": "DC_PRODUCTOSNC", "p": [5] },
	{ "s": "DC_PRODUCTOSOC", "p": [5] },
	{ "s": "DC_PRODUCTOSREEMBOLSO", "p": [5] },
	{ "s": "DC_PRODUCTOSSIGA", "p": [5] },
	{ "s": "DC_PRODUCTOSTRANSPORTE", "p": [5] },
	{ "s": "DC_PRODUCTOSTRANSPORTENC", "p": [5] },
	{ "s": "DC_PUERTOS", "p": [5] },
	{ "s": "DC_PUERTOS_PUERTOS", "p": [5] },
	{ "s": "DC_RAZONESDERECHAZO", "p": [5] },
	{ "s": "DC_RECIBOS", "p": [5] },
	{ "s": "DC_RESERVAS", "p": [5] },
	{ "s": "DC_SALESLEADS", "p": [5] },
	{ "s": "DC_SUPLIDOR", "p": [7, 6] },
	{ "s": "DC_SUPLIDORADUANAS", "p": [7, 6] },
	{ "s": "DC_SUPLIDORDEVENTAS", "p": [7, 6] },
	{ "s": "DC_SUPLIDOREMBARQUE", "p": [7, 6] },
	{ "s": "DC_SUPLIDORTRANSPORTE", "p": [7, 6] },
	{ "s": "DC_TARIFACOMISIONES", "p": [5] },
	{ "s": "DC_TARIFAESCALONADA", "p": [5] },
	{ "s": "DC_TASA", "p": [5] },
	{ "s": "DC_TIPODEBULTOS", "p": [5] },
	{ "s": "DC_TIPODECAMBIO", "p": [5] },
	{ "s": "DC_TIPODEVEHICULO", "p": [5] },
	{ "s": "DC_TRANSACCIONESCOMISIONES", "p": [5] },
	{ "s": "DC_TRANSPORTE", "p": [7, 6, 5] },
	{ "s": "DC_TRANSPORTEID", "p": [6] },
	{ "s": "DC_TRANSPORTISTA", "p": [7, 6] },
	{ "s": "DC_TRATADOSADUANALES", "p": [5] },
	{ "s": "DC_VEHICULOS", "p": [5] },
	{ "s": "DC_VEHICULOSEMBARQUES", "p": [5] },
	{ "s": "DC_VOLUMENMARITIMO", "p": [5] },
	{ "s": "DE", "p": [8, 4, 5, 7, 3, 6, 1] },
	{ "s": "DEBE", "p": [8] },
	{ "s": "DEBEN", "p": [8] },
	{ "s": "DEBES", "p": [8] },
	{ "s": "DEBIDO", "p": [8] },
	{ "s": "DECIDE", "p": [8] },
	{ "s": "DECLARACIONES", "p": [5] },
	{ "s": "DEFINE", "p": [8] },
	{ "s": "DEFINICIONES", "p": [4] },
	{ "s": "DEFINICIÓN", "p": [6] },
	{ "s": "DEFINIR", "p": [8, 4] },
	{ "s": "DEL", "p": [8, 3, 7, 4] },
	{ "s": "DELETE", "p": [8, 3] },
	{ "s": "DEPURACIÓN", "p": [8] },
	{ "s": "DEPÓSITOS", "p": [5] },
	{ "s": "DESCRIPTIVO", "p": [8] },
	{ "s": "DESDE", "p": [8] },
	{ "s": "DESEA", "p": [8] },
	{ "s": "DESEAS", "p": [8] },
	{ "s": "DESPACHO", "p": [5] },
	{ "s": "DESPUÉS", "p": [8] },
	{ "s": "DETALLA", "p": [8] },
	{ "s": "DETALLADA", "p": [8] },
	{ "s": "DETALLES", "p": [8] },
	{ "s": "DETENIDA", "p": [8] },
	{ "s": "DEVELOPER", "p": [8] },
	{ "s": "DIARIO", "p": [8] },
	{ "s": "DIF", "p": [5] },
	{ "s": "DIFERENTES", "p": [8, 4] },
	{ "s": "DISCUTIDO", "p": [8] },
	{ "s": "DISEÑADA", "p": [4] },
	{ "s": "DISEÑADO", "p": [8] },
	{ "s": "DISPLAY", "p": [5] },
	{ "s": "DISTRIBUCIÓN", "p": [5] },
	{ "s": "DIVERSAS", "p": [8] },
	{ "s": "DOCUMENTACIÓN", "p": [8, 1] },
	{ "s": "DOCUMENTOS", "p": [5] },
	{ "s": "DOCUMENTS", "p": [5] },
	{ "s": "DONDE", "p": [7] },
	{ "s": "DURACIÓN", "p": [8] },
	{ "s": "DURANTE", "p": [8] },
	{ "s": "DYNACORP", "p": [4] },
	{ "s": "DYNAMICS", "p": [8, 4] }
];