DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0053"] = [
	{ "s": "SALES", "p": [5] },
	{ "s": "SE", "p": [8, 4] },
	{ "s": "SEAN", "p": [8] },
	{ "s": "SEGMENTA", "p": [4] },
	{ "s": "SEGUNDO", "p": [8] },
	{ "s": "SEGURIDAD", "p": [4] },
	{ "s": "SEGURO", "p": [4] },
	{ "s": "SELECCIONA", "p": [8] },
	{ "s": "SELECCIONAR", "p": [8] },
	{ "s": "SEMANAL", "p": [8] },
	{ "s": "SER", "p": [8, 7] },
	{ "s": "SERVICE", "p": [8] },
	{ "s": "SESIONES", "p": [8] },
	{ "s": "SESSIONS", "p": [8] },
	{ "s": "SHAREPOINT", "p": [5] },
	{ "s": "SI", "p": [8] },
	{ "s": "SIENDO", "p": [8] },
	{ "s": "SIGA", "p": [5, 8] },
	{ "s": "SIGUIENDO", "p": [8] },
	{ "s": "SIGUIENTE", "p": [8] },
	{ "s": "SIMILAR", "p": [4] },
	{ "s": "SINCRÓNICAS", "p": [8] },
	{ "s": "SIRVE", "p": [4] },
	{ "s": "SISTEMA", "p": [8, 4, 3] },
	{ "s": "SISTEMAS", "p": [7] },
	{ "s": "SOBRE", "p": [8, 4] },
	{ "s": "SOLO", "p": [8, 6] },
	{ "s": "SON", "p": [8, 7, 4] },
	{ "s": "STATUS", "p": [8] },
	{ "s": "SU", "p": [8, 4, 3] },
	{ "s": "SUGIERE", "p": [7] },
	{ "s": "SUPLIDOR", "p": [7] },
	{ "s": "SUSPENDED", "p": [8] },
	{ "s": "SUSPENDER", "p": [8] },
	{ "s": "SUSPENDIDO", "p": [8] },
	{ "s": "SYSTEM", "p": [8, 3] },
	{ "s": "SÍ", "p": [7] }
];