DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0043"] = [
	{ "s": "CADA", "p": [4] },
	{ "s": "CALL", "p": [5] },
	{ "s": "CAMBIO", "p": [5] },
	{ "s": "CAMBIOS", "p": [8] },
	{ "s": "CAMPOS", "p": [4] },
	{ "s": "CANCELADO", "p": [8] },
	{ "s": "CANCELAR", "p": [8] },
	{ "s": "CANCELED", "p": [8] },
	{ "s": "CANTIDAD", "p": [8] },
	{ "s": "CAPACIDAD", "p": [4] },
	{ "s": "CAPACIDADES", "p": [4] },
	{ "s": "CARACTERIZAN", "p": [8] },
	{ "s": "CARACTERÍSTICAS", "p": [4] },
	{ "s": "CARGOS", "p": [5] },
	{ "s": "CASO", "p": [8] },
	{ "s": "CENTRAL", "p": [7] },
	{ "s": "CENTRALIZA", "p": [4] },
	{ "s": "CENTRALIZADA", "p": [8] },
	{ "s": "CENTRALIZAN", "p": [8] },
	{ "s": "CENTRO", "p": [8] },
	{ "s": "CERTIFICADOS", "p": [5] },
	{ "s": "CHASIS", "p": [5] },
	{ "s": "CLARAS", "p": [8] },
	{ "s": "CLAVE", "p": [6, 7, 4, 3] },
	{ "s": "CLAVES", "p": [7, 6, 3] },
	{ "s": "CLIC", "p": [8] },
	{ "s": "CLIENTE", "p": [7, 5] },
	{ "s": "CLOUD", "p": [8] },
	{ "s": "CLÁSICA", "p": [8] },
	{ "s": "COLECCIÓN", "p": [4] },
	{ "s": "COLECTAR", "p": [5] },
	{ "s": "COLUMNA", "p": [4] },
	{ "s": "COLUMNAS", "p": [4] },
	{ "s": "COM", "p": [8] },
	{ "s": "COMANDOS", "p": [8] },
	{ "s": "COMISIONES", "p": [5] },
	{ "s": "COMMON", "p": [8] },
	{ "s": "COMO", "p": [8, 4, 7] },
	{ "s": "COMPLEJO", "p": [7] },
	{ "s": "COMPLETADAS", "p": [8] },
	{ "s": "COMPLETADO", "p": [8] },
	{ "s": "COMPLETADOS", "p": [8] },
	{ "s": "COMPLETADOS/FALLIDOS", "p": [8] },
	{ "s": "COMPLETED", "p": [8] },
	{ "s": "COMPLETÓ", "p": [8] },
	{ "s": "COMPONENTES", "p": [4] },
	{ "s": "COMPRA", "p": [5] },
	{ "s": "COMPRAS", "p": [5] },
	{ "s": "COMUNES", "p": [8] },
	{ "s": "COMÚN", "p": [8] },
	{ "s": "CON", "p": [7, 8, 4, 3] },
	{ "s": "CONCENTRAREMOS", "p": [8] },
	{ "s": "CONCEPTO", "p": [4] },
	{ "s": "CONEXIONES", "p": [4] },
	{ "s": "CONFIGURACIÓN", "p": [8, 5] },
	{ "s": "CONFIGURAR", "p": [8] },
	{ "s": "CONJUNTOS", "p": [4] },
	{ "s": "CONOCIDO", "p": [8] },
	{ "s": "CONSERVARSE", "p": [8] },
	{ "s": "CONSIDERACIONES", "p": [8, 3] },
	{ "s": "CONSIGNATARIO", "p": [7] },
	{ "s": "CONSOLA", "p": [8] },
	{ "s": "CONSOLIDADO", "p": [5] },
	{ "s": "CONSULTA", "p": [8] },
	{ "s": "CONSULTAS", "p": [8] },
	{ "s": "CONSUMEN", "p": [8] },
	{ "s": "CONSUMO", "p": [8] },
	{ "s": "CONTACT", "p": [5] },
	{ "s": "CONTACTOS", "p": [5] },
	{ "s": "CONTENDRÍA", "p": [6] },
	{ "s": "CONTENEDORES", "p": [5] },
	{ "s": "CONTEXTO", "p": [4] },
	{ "s": "CONTINUACIÓN", "p": [4] },
	{ "s": "CONTROL", "p": [8] },
	{ "s": "CONVENCIÓN", "p": [6] },
	{ "s": "CORREO", "p": [8] },
	{ "s": "CORREOS", "p": [4] },
	{ "s": "CORRESPONDIENTE", "p": [8] },
	{ "s": "COTIZACIONES", "p": [7, 5] },
	{ "s": "COTIZACIÓN", "p": [5] },
	{ "s": "CREACIÓN", "p": [8] },
	{ "s": "CREADAS", "p": [8] },
	{ "s": "CREADO", "p": [8] },
	{ "s": "CREAN", "p": [8] },
	{ "s": "CREAR", "p": [8] },
	{ "s": "CREARLO", "p": [8] },
	{ "s": "CREARÁ", "p": [8] },
	{ "s": "CREATED", "p": [8] },
	{ "s": "CRECIMIENTO", "p": [8] },
	{ "s": "CRITERIOS", "p": [8] },
	{ "s": "CRUCIAL", "p": [8] },
	{ "s": "CRÉDITO", "p": [5] },
	{ "s": "CUAL", "p": [8, 7, 4] },
	{ "s": "CUALQUIER", "p": [8] },
	{ "s": "CUANDO", "p": [8] },
	{ "s": "CUENTA", "p": [8, 7] },
	{ "s": "CUMPLIR", "p": [8] },
	{ "s": "CURRENCY", "p": [5] },
	{ "s": "CURSO", "p": [8] },
	{ "s": "CUÁNDO", "p": [8] },
	{ "s": "CUÁNTO", "p": [8] },
	{ "s": "CÁLCULO", "p": [4] },
	{ "s": "CÓDIGO", "p": [5] }
];