DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0050"] = [
	{ "s": "PADRES", "p": [7] },
	{ "s": "PADRES/HIJOS", "p": [7] },
	{ "s": "PARA", "p": [8, 4, 7, 6] },
	{ "s": "PASADAS", "p": [8] },
	{ "s": "PASO", "p": [8] },
	{ "s": "PASOS", "p": [8] },
	{ "s": "PAUSADO", "p": [8] },
	{ "s": "PAÍS", "p": [5] },
	{ "s": "PENALIDAD", "p": [5] },
	{ "s": "PENDIENTE", "p": [8] },
	{ "s": "PERFIL", "p": [5] },
	{ "s": "PERFILES", "p": [5] },
	{ "s": "PERIÓDICA", "p": [8] },
	{ "s": "PERIÓDICAMENTE", "p": [8] },
	{ "s": "PERMANENTE", "p": [8] },
	{ "s": "PERMITE", "p": [8, 4] },
	{ "s": "PERO", "p": [8, 4] },
	{ "s": "PERSONAL", "p": [8] },
	{ "s": "PESO", "p": [5] },
	{ "s": "PHONE", "p": [5] },
	{ "s": "PK", "p": [6, 7, 3] },
	{ "s": "PLANIFICACIÓN", "p": [8] },
	{ "s": "PLANO", "p": [8] },
	{ "s": "PLATFORM", "p": [8, 4] },
	{ "s": "POCO", "p": [8] },
	{ "s": "PODEMOS", "p": [8] },
	{ "s": "PODRÁS", "p": [8] },
	{ "s": "POLÍTICAS", "p": [8] },
	{ "s": "POR", "p": [8, 6, 4] },
	{ "s": "POSIBLE", "p": [8] },
	{ "s": "POSIBLEMENTE", "p": [7] },
	{ "s": "POSITION", "p": [5] },
	{ "s": "POWER", "p": [8, 4] },
	{ "s": "POWERPLATFORM", "p": [8] },
	{ "s": "PRECAUCIÓN", "p": [8] },
	{ "s": "PRECIOS", "p": [5] },
	{ "s": "PRIMARIA", "p": [6, 7, 3] },
	{ "s": "PRIMARIAS", "p": [7, 3] },
	{ "s": "PRIMERA", "p": [8] },
	{ "s": "PRINCIPAL", "p": [8, 7] },
	{ "s": "PROCESA", "p": [8] },
	{ "s": "PROCESO", "p": [8] },
	{ "s": "PROCESOS", "p": [8] },
	{ "s": "PROCESS", "p": [8] },
	{ "s": "PRODUCTOS", "p": [5] },
	{ "s": "PROGRAMA", "p": [8] },
	{ "s": "PROGRAMAR", "p": [8] },
	{ "s": "PROGRESS", "p": [8] },
	{ "s": "PROPIA", "p": [8] },
	{ "s": "PROPIETARIO", "p": [8] },
	{ "s": "PROPIOS", "p": [8] },
	{ "s": "PRÁCTICAS", "p": [8, 3] },
	{ "s": "PUEDE", "p": [8, 7] },
	{ "s": "PUEDEN", "p": [8] },
	{ "s": "PUEDES", "p": [8] },
	{ "s": "PUERTOS", "p": [5] },
	{ "s": "PUNTUAL", "p": [8] },
	{ "s": "PURGA", "p": [8, 3] },
	{ "s": "PURGADOS", "p": [8] },
	{ "s": "PURGAR", "p": [8] }
];