DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex.prefixes = [
	{ "fileName": "0xu0031.js", "first": "1", "last": "1:N" },
	{ "fileName": "0xu0032.js", "first": "2", "last": "2025" },
	{ "fileName": "0xu0033.js", "first": "3", "last": "365/COMMON" },
	{ "fileName": "0xu0034.js", "first": "4", "last": "4.5" },
	{ "fileName": "0xu0035.js", "first": "5", "last": "5" },
	{ "fileName": "0xu0036.js", "first": "6", "last": "6" },
	{ "fileName": "0xu0037.js", "first": "7", "last": "7" },
	{ "fileName": "0xu0038.js", "first": "8", "last": "8" },
	{ "fileName": "0xu0039.js", "first": "9", "last": "9" },
	{ "fileName": "0xu0041.js", "first": "A", "last": "AÑO" },
	{ "fileName": "0xu0042.js", "first": "BAJA", "last": "BÚSQUEDA" },
	{ "fileName": "0xu0043.js", "first": "CADA", "last": "CÓDIGO" },
	{ "fileName": "0xu0044.js", "first": "DATA", "last": "DYNAMICS" },
	{ "fileName": "0xu0045.js", "first": "EFICAZMENTE", "last": "EXTREMA" },
	{ "fileName": "0xu0046.js", "first": "FACTURA", "last": "FÍSICA" },
	{ "fileName": "0xu0047.js", "first": "GENERADA", "last": "GUIDE" },
	{ "fileName": "0xu0048.js", "first": "HABILITA", "last": "HTTPS://LEARN.MICROSOFT.COM/EN-US/POWER-APPS/DEVELOPER/DATA-PLATFORM/ASYNCHRONOUS-SERVICE?TABS" },
	{ "fileName": "0xu0049.js", "first": "ICONO", "last": "IR" },
	{ "fileName": "0xu004a.js", "first": "JERARQUÍA", "last": "JUSTO" },
	{ "fileName": "0xu004c.js", "first": "LA", "last": "LÓGICOS" },
	{ "fileName": "0xu004d.js", "first": "MAESTRO", "last": "MÚLTIPLES" },
	{ "fileName": "0xu004e.js", "first": "N", "last": "NÚMERO" },
	{ "fileName": "0xu004f.js", "first": "O", "last": "OTROS" },
	{ "fileName": "0xu0050.js", "first": "PADRES", "last": "PURGAR" },
	{ "fileName": "0xu0051.js", "first": "QUE", "last": "QUÉ" },
	{ "fileName": "0xu0052.js", "first": "RAZONES", "last": "RÁPIDAS" },
	{ "fileName": "0xu0053.js", "first": "SALES", "last": "SÍ" },
	{ "fileName": "0xu0054.js", "first": "TABLA", "last": "TÍPICO" },
	{ "fileName": "0xu0055.js", "first": "UN", "last": "UTILIZANDO" },
	{ "fileName": "0xu0056.js", "first": "VARIAS", "last": "VOLÚMENES" },
	{ "fileName": "0xu0057.js", "first": "WAITING", "last": "WORKFLOWS/FLOWS" },
	{ "fileName": "0xu0059.js", "first": "Y", "last": "YA" },
	{ "fileName": "0xu00c9.js", "first": "ÉXITO", "last": "ÉXITO" },
	{ "fileName": "0xu00cd.js", "first": "ÍNDICE", "last": "ÍNDICE" },
	{ "fileName": "0xu00d3.js", "first": "ÓRDENES", "last": "ÓRDENES" }
];