DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0050"] = [
	{ "s": "PADRE", "p": [7] },
	{ "s": "PANEL", "p": [7, 10, 6] },
	{ "s": "PARA", "p": [8, 11, 7, 10, 12, 9, 6] },
	{ "s": "PARTE", "p": [10, 7, 11] },
	{ "s": "PARÁMETRO", "p": [12] },
	{ "s": "PARÁMETROS", "p": [12, 8] },
	{ "s": "PASO", "p": [8, 9, 11, 6] },
	{ "s": "PASOS", "p": [9, 11, 13, 8] },
	{ "s": "PASTE", "p": [9] },
	{ "s": "PATH", "p": [9, 8] },
	{ "s": "PAÍS", "p": [11] },
	{ "s": "PAÍSES", "p": [11] },
	{ "s": "PELIGROSOS", "p": [11] },
	{ "s": "PERIODO", "p": [12] },
	{ "s": "PERMISOS", "p": [7, 11, 10] },
	{ "s": "PERMITE", "p": [11, 7, 8] },
	{ "s": "PERMITIDOS", "p": [11] },
	{ "s": "PERMITIR", "p": [11] },
	{ "s": "PERO", "p": [10] },
	{ "s": "PERSONALIZADOR", "p": [10] },
	{ "s": "PERSONAS", "p": [7] },
	{ "s": "PERTENENCIA", "p": [11] },
	{ "s": "PERTENEZCAN", "p": [7] },
	{ "s": "PERÍODO", "p": [12] },
	{ "s": "PLAN", "p": [7] },
	{ "s": "PLANO", "p": [10] },
	{ "s": "PLANTILLA", "p": [11] },
	{ "s": "PLATAFORMAS", "p": [11] },
	{ "s": "PLATFORM", "p": [8, 10, 9, 7, 11, 6, 5, 4, 3] },
	{ "s": "PODEMOS", "p": [13, 8] },
	{ "s": "PODER", "p": [12] },
	{ "s": "PODRÁN", "p": [11] },
	{ "s": "POLICY", "p": [11] },
	{ "s": "POLÍTICA", "p": [11] },
	{ "s": "POR", "p": [11, 10, 9, 13, 12, 8, 3] },
	{ "s": "PORTAL", "p": [11] },
	{ "s": "POSIBLE", "p": [10] },
	{ "s": "POSIBLES", "p": [11] },
	{ "s": "POSTERIORMENTE", "p": [8] },
	{ "s": "POWER", "p": [8, 10, 9, 7, 11, 6, 5, 4, 3] },
	{ "s": "POWERAPPENVIRONMENT", "p": [8, 9] },
	{ "s": "POWERAPPS", "p": [9, 8, 10] },
	{ "s": "POWERAPPSACCOUNT", "p": [8, 9, 10] },
	{ "s": "POWERPLATFORM", "p": [6, 5] },
	{ "s": "POWERSHELL", "p": [8, 10, 9, 12, 3] },
	{ "s": "PPAC", "p": [9] },
	{ "s": "PRECISIÓN", "p": [8] },
	{ "s": "PREPARACIÓN", "p": [8] },
	{ "s": "PREPARAR", "p": [9, 8, 3] },
	{ "s": "PREPARATION", "p": [9] },
	{ "s": "PREPARE", "p": [9] },
	{ "s": "PREPAREMIGRATION", "p": [9, 8] },
	{ "s": "PREPARING", "p": [9] },
	{ "s": "PRESENTE", "p": [8] },
	{ "s": "PREVIA", "p": [8] },
	{ "s": "PREVIOUS", "p": [9] },
	{ "s": "PRIMARY", "p": [9] },
	{ "s": "PRINCIPALES", "p": [11] },
	{ "s": "PRIVILEGIO", "p": [10] },
	{ "s": "PRIVILEGIOS", "p": [11, 10, 7] },
	{ "s": "PROBLEMA", "p": [12, 11, 9] },
	{ "s": "PROBLEMAS", "p": [11] },
	{ "s": "PROCEDEMOS", "p": [11, 12, 9, 6, 5] },
	{ "s": "PROCESO", "p": [8, 6, 10, 3, 12, 5, 4] },
	{ "s": "PROCESOS", "p": [13] },
	{ "s": "PROD", "p": [9, 10] },
	{ "s": "PRODUCCIÓN", "p": [4, 10, 3, 12] },
	{ "s": "PRODUCTION", "p": [12] },
	{ "s": "PRODUCTIVOS", "p": [11] },
	{ "s": "PROFUNDO", "p": [7] },
	{ "s": "PROGRESO", "p": [8] },
	{ "s": "PROPIEDAD", "p": [10] },
	{ "s": "PROPIO", "p": [10, 9] },
	{ "s": "PROPORCIONA", "p": [11, 8] },
	{ "s": "PROPORCIONAR", "p": [8] },
	{ "s": "PROPORCIONARÁ", "p": [9] },
	{ "s": "PROPORCIONE", "p": [12] },
	{ "s": "PROTECCIÓN", "p": [11] },
	{ "s": "PROTECTION", "p": [11] },
	{ "s": "PROTECTIONLEVEL", "p": [10] },
	{ "s": "PROTEGER", "p": [11] },
	{ "s": "PROTOCOLOS", "p": [11] },
	{ "s": "PROVIDE", "p": [9] },
	{ "s": "PRUEBA", "p": [10] },
	{ "s": "PSCUSTOMOBJECT", "p": [10] },
	{ "s": "PSGALLERY", "p": [9] },
	{ "s": "PUEDA", "p": [6] },
	{ "s": "PUEDAN", "p": [10] },
	{ "s": "PUEDE", "p": [8, 10, 12, 11, 9] },
	{ "s": "PUEDEN", "p": [11, 7, 10] },
	{ "s": "PUT", "p": [10] },
	{ "s": "PÁGINA", "p": [7, 11, 10] }
];