DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0044"] = [
	{ "s": "D", "p": [5] },
	{ "s": "DADO", "p": [7] },
	{ "s": "DAMOS", "p": [5] },
	{ "s": "DARLE", "p": [6] },
	{ "s": "DATOS", "p": [7, 8] },
	{ "s": "DE", "p": [11, 8, 7, 10, 3, 9, 12, 5, 6, 4, 13] },
	{ "s": "DEBE", "p": [8, 12, 10, 7, 11, 9] },
	{ "s": "DEBEMOS", "p": [13, 12, 8, 6] },
	{ "s": "DEBEN", "p": [9, 11] },
	{ "s": "DEBERÁ", "p": [9] },
	{ "s": "DECISIONES", "p": [11, 3] },
	{ "s": "DECISIÓN", "p": [11] },
	{ "s": "DEFINE", "p": [9] },
	{ "s": "DEL", "p": [8, 11, 10, 7, 9, 5, 12, 6, 3] },
	{ "s": "DEMORA", "p": [6] },
	{ "s": "DEMÁS", "p": [8] },
	{ "s": "DENEGADOS", "p": [11] },
	{ "s": "DENY", "p": [8] },
	{ "s": "DESACTIVAR", "p": [10] },
	{ "s": "DESCARGAR", "p": [9] },
	{ "s": "DESCRIBE", "p": [10] },
	{ "s": "DESCRIPCIÓN", "p": [7] },
	{ "s": "DESDE", "p": [11, 9] },
	{ "s": "DESEA", "p": [10, 7, 11] },
	{ "s": "DESEADO", "p": [4] },
	{ "s": "DESEAMOS", "p": [13, 6, 5] },
	{ "s": "DESHABILITAR", "p": [10, 3] },
	{ "s": "DESHABILITAR/APAGAR", "p": [10] },
	{ "s": "DESHABILITARLOS", "p": [10] },
	{ "s": "DESPUÉS", "p": [9, 6, 5] },
	{ "s": "DESTINAR", "p": [11] },
	{ "s": "DESTINATION", "p": [9] },
	{ "s": "DESTINATIONPATH", "p": [9] },
	{ "s": "DESTINO", "p": [8, 11, 9] },
	{ "s": "DETALLES", "p": [10, 11] },
	{ "s": "DETECCIÓN", "p": [11] },
	{ "s": "DIAGNÓSTICO", "p": [11, 3] },
	{ "s": "DIAGNÓSTICOS", "p": [11] },
	{ "s": "DIF", "p": [4] },
	{ "s": "DIFERENTES", "p": [11] },
	{ "s": "DIRECCIONES", "p": [11] },
	{ "s": "DIRECCIÓN", "p": [8, 7] },
	{ "s": "DIRECTIVA", "p": [11] },
	{ "s": "DIRECTIVAS", "p": [11, 3] },
	{ "s": "DIRIGIRSE", "p": [11] },
	{ "s": "DISPONIBLES", "p": [5] },
	{ "s": "DISPOSITIVO", "p": [11] },
	{ "s": "DISPOSITIVOS", "p": [11] },
	{ "s": "DIVERSA", "p": [13] },
	{ "s": "DNSSAFEHOST", "p": [8] },
	{ "s": "DOBLES", "p": [8] },
	{ "s": "DOCUMENTACIÓN", "p": [2, 11, 10, 1] },
	{ "s": "DOMINICANA", "p": [11] },
	{ "s": "DONDE", "p": [11, 8, 7, 6] },
	{ "s": "DOS", "p": [5, 11] },
	{ "s": "DOWNLOAD", "p": [9] },
	{ "s": "DOWNLOADED", "p": [9] },
	{ "s": "DOWNLOADS", "p": [9] },
	{ "s": "DURACIÓN", "p": [8] },
	{ "s": "DURANTE", "p": [11] },
	{ "s": "DYNAMICS", "p": [8, 9] },
	{ "s": "DÍAS", "p": [12, 13, 11] }
];