DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex.ids = {
	"1": ["Title", "index.htm", []],
	"2": ["Manual de Usuario | Sistema Dynacorp", "manual_de_usuario___sistema_dynacorp.htm", []],
	"3": ["Índice", "indice.htm", [1]],
	"4": ["3. Módulo de Ventas", "3__modulo_de_ventas.htm", []],
	"5": ["3.1 Crear un Prospecto", "3_1_crear_un_prospecto.htm", [2]],
	"6": ["Paso a Paso: Crear un Prospecto", "paso_a_paso__crear_un_prospecto.htm", [2,12]],
	"7": ["3.2 Crear una Oportunidad", "3_2_crear_una_oportunidad.htm", [2]],
	"8": ["3.3 Convertir una Oportunidad en Cotización", "3_3_convertir_una_oportunidad_en_cotizacion.htm", [2]],
	"9": ["3.4 Crear Lista de Precios", "3_4_crear_lista_de_precios.htm", [2]],
	"10": ["Paso a Paso: Crear Lista de Precios", "paso_a_paso__crear_lista_de_precios.htm", [2,15]],
	"11": ["3.5 Agregar Productos a la Lista de Precios", "3_5_agregar_productos_a_la_lista_de_precios.htm", [2]],
	"12": ["Paso a Paso: Agregar Productos a Lista de Precios", "paso_a_paso__agregar_productos_a_lista_de_precios.htm", [2,16]],
	"13": ["3.6 Enviar Cotización al Cliente", "3_6_enviar_cotizacion_al_cliente.htm", [2]],
	"14": ["Paso a Paso: Enviar Cotización a Cliente", "paso_a_paso__enviar_cotizacion_a_cliente.htm", [2,17]],
	"15": ["3.7 Aprobar o Rechazar Cotización", "3_7_aprobar_o_rechazar_cotizacion.htm", [2]],
	"16": ["Paso a Paso: Aprobar y Rechazar una Cotización", "paso_a_paso__aprobar_y_rechazar_una_cotizacion.htm", [2,18]],
	"17": ["4. Módulos de Embarques y Trafico", "4__modulos_de_embarques_y_trafico.htm", []],
	"18": ["4.1 Crear una Orden de Embarque (HBL)", "4_1_crear_una_orden_de_embarque__hbl_.htm", [3]],
	"19": ["Paso a Paso: Crear una Orden de Embarque(HBL)", "paso_a_paso__crear_una_orden_de_embarque_hbl_.htm", [3,19]],
	"20": ["4.2 Agregar Booking, BL y Transportista", "4_2_agregar_booking__bl_y_transportista.htm", [3]],
	"21": ["Paso a Paso: Agregar Booking, BL, Transportista", "paso_a_paso__agregar_booking__bl__transportista.htm", [3,20]],
	"22": ["4.3 Estados del Embarque (ETA, ATD, ATA, ETD)", "4_3_estados_del_embarque__eta__atd__ata__etd_.htm", [3]],
	"23": ["Estados del Embarque", "estados_del_embarque.htm", [3,21]],
	"24": ["4.4 Documentos Obligatorios y Carga de Archivos", "4_4_documentos_obligatorios_y_carga_de_archivos.htm", [3]],
	"25": ["Documentos Obligatorios y Carga de Archivos", "documentos_obligatorios_y_carga_de_archivos.htm", [3,22]],
	"26": ["4.5 Facturación Automática", "4_5_facturacion_automatica.htm", [3]],
	"27": ["Paso a Paso: Facturación Automática", "paso_a_paso__facturacion_automatica.htm", [3,23]],
	"28": ["4.6 Módulo de Tráfico: Seguimiento y Liberación", "4_6_modulo_de_trafico__seguimiento_y_liberacion.htm", [3]],
	"29": ["Paso a Paso: Liberar una Carga", "paso_a_paso__liberar_una_carga.htm", [3,24]],
	"30": ["4.7 Consolidado (MBL) y Contenedores", "4_7_consolidado__mbl__y_contenedores.htm", [3]],
	"31": ["Paso a Paso: Crear Consolidado / Vincular HBL / Agregar Contenedor al Consolidado", "paso_a_paso__crear_consolidado___vincular_hbl___agregar_contenedor_al_consolidado.htm", [3,25]],
	"32": ["4.8 Carga de Vehículos", "4_8_carga_de_vehiculos.htm", [3]],
	"33": ["Paso a Paso: Carga de Vehiculo", "paso_a_paso__carga_de_vehiculo.htm", [3,26]],
	"34": ["4.9 Incidencias y Validación por Finanzas", "4_9_incidencias_y_validacion_por_finanzas.htm", [3]],
	"35": ["Paso a paso: Crear Incidencia en Embarques", "paso_a_paso__crear_incidencia_en_embarques.htm", [3,27]],
	"36": ["5. Módulo de Aduanas", "5__modulo_de_aduanas.htm", []],
	"37": ["5.1. Crear Orden de Aduana", "5_1__crear_orden_de_aduana.htm", [4]],
	"38": ["5.2 Carga de Productos Arancelarios y Declaración en SIGA", "5_2_carga_de_productos_arancelarios_y_declaracion_en_siga.htm", [4]],
	"39": ["Paso a Paso: Generar XML", "paso_a_paso__generar_xml.htm", [4,29]],
	"40": ["5.3 Coordinación con Agentes, Depósitos y Seguimiento de Liberación", "5_3_coordinacion_con_agentes__depositos_y_seguimiento_de_liberacion.htm", [4]],
	"41": ["5.4 Facturación, Reembolsos y Cierre de Orden de Aduana", "5_4_facturacion__reembolsos_y_cierre_de_orden_de_aduana.htm", [4]],
	"42": ["Paso a Paso: Facturar Orden de Aduana / Reembolso / Cierre", "paso_a_paso__facturar_orden_de_aduana___reembolso___cierre.htm", [4,31]],
	"43": ["6. Módulo de Transporte", "6__modulo_de_transporte.htm", []],
	"44": ["6.1 Crear un Transporte", "6_1_crear_un_transporte.htm", [5]],
	"45": ["Paso a Paso: Crear un Transporte", "paso_a_paso__crear_un_transporte.htm", [5,32]],
	"46": ["6.2 Registro del Despacho y Seguimiento Logístico", "6_2_registro_del_despacho_y_seguimiento_logistico.htm", [5]],
	"47": ["6. 3 Facturación del Transporte y Reembolsos", "6__3_facturacion_del_transporte_y_reembolsos.htm", [5]],
	"48": ["Paso a Paso: Generar Factura de Transporte", "paso_a_paso__generar_factura_de_transporte.htm", [5,34]],
	"49": ["Paso a Paso: Reembolso de Transporte", "paso_a_paso__reembolso_de_transporte.htm", [5,34]],
	"50": ["6.4. Control de Incidencias y Estados Logísticos", "6_4__control_de_incidencias_y_estados_logisticos.htm", [5]],
	"51": ["Paso a Paso: Registrar Incidencias", "paso_a_paso__registrar_incidencias.htm", [5,35]],
	"52": ["6.5. Maestro de Vehículos, Choferes y Localidades", "6_5__maestro_de_vehiculos__choferes_y_localidades.htm", [5]],
	"53": ["Paso a Paso: Registrar un Nuevo Vehículo", "paso_a_paso__registrar_un_nuevo_vehiculo.htm", [5,36]],
	"54": ["Paso a Paso: Registrar Conductor", "paso_a_paso__registrar_conductor.htm", [5,36]],
	"55": ["Paso a Paso: Registrar Localidades", "paso_a_paso__registrar_localidades.htm", [5,36]],
	"56": ["7. Módulo de Contabilidad", "7__modulo_de_contabilidad.htm", []],
	"57": ["7.1. Crear Factura", "7_1__crear_factura.htm", [6]],
	"58": ["7.2. Órdenes de Compra", "7_2__ordenes_de_compra.htm", [6]],
	"59": ["Paso a Paso: Crear Orden de Compra", "paso_a_paso__crear_orden_de_compra.htm", [6,38]],
	"60": ["7.3 Notas de Crédito", "7_3_notas_de_credito.htm", [6]],
	"61": ["Paso a Paso: Crear Nota de Crédito", "paso_a_paso__crear_nota_de_credito.htm", [6,39]],
	"62": ["7.4 Créditos de Agente", "7_4_creditos_de_agente.htm", [6]],
	"63": ["Paso a Paso: Registrar un Crédito de Agente", "paso_a_paso__registrar_un_credito_de_agente.htm", [6,40]],
	"64": ["7.5 Exportación de Facturas y Notas de Crédito", "7_5_exportacion_de_facturas_y_notas_de_credito.htm", [6]],
	"65": ["Paso a Paso: Exportar Facturas y Notas de Crédito", "paso_a_paso__exportar_facturas_y_notas_de_credito.htm", [6,41]],
	"66": ["7.6 Vista General de Facturación por Entidad", "7_6_vista_general_de_facturacion_por_entidad.htm", [6]],
	"67": ["Paso a Paso: Visualización desde Contabilidad", "paso_a_paso__visualizacion_desde_contabilidad.htm", [6,42]],
	"68": ["Paso a Paso: Visualización desde l Entidad", "paso_a_paso__visualizacion_desde_l_entidad.htm", [6,42]],
	"69": ["8. Módulo de Configuración", "8__modulo_de_configuracion.htm", []],
	"70": ["8.1 Catálogo de Productos y Tipos", "8_1_catalogo_de_productos_y_tipos.htm", [7]],
	"71": ["Paso a paso: Crear Nuevo Producto", "paso_a_paso__crear_nuevo_producto.htm", [7,43]],
	"72": ["8. 2. Catálogo de Países y Códigos ISO", "8__2__catalogo_de_paises_y_codigos_iso.htm", [7]],
	"73": ["Paso a Paso: Registrar un Nuevo Producto", "paso_a_paso__registrar_un_nuevo_producto.htm", [7,44]],
	"74": ["8.3 Catálogo de Puertos y Agrupaciones", "8_3_catalogo_de_puertos_y_agrupaciones.htm", [7]],
	"75": ["Paso a Paso: Registrar un Nuevo Puerto", "paso_a_paso__registrar_un_nuevo_puerto.htm", [7,45]],
	"76": ["8.4 Tipos de Bultos y Unidades de Medida", "8_4_tipos_de_bultos_y_unidades_de_medida.htm", [7]],
	"77": ["Paso a Paso: Registrar un Tipo de Bulto", "paso_a_paso__registrar_un_tipo_de_bulto.htm", [7,46]],
	"78": ["8.5 Tasas de Cambio", "8_5_tasas_de_cambio.htm", [7]],
	"79": ["Paso a paso: Registrar una Tasa de Cambio", "paso_a_paso__registrar_una_tasa_de_cambio.htm", [7,47]],
	"80": ["8.6 Homologaciones para SIGA ", "8_6_homologaciones_para_siga_.htm", [7]],
	"81": ["Homologaciones para SIGA", "homologaciones_para_siga.htm", [7,48]],
	"82": ["8.7 Integraciones API con Magaya, DGA, Dynamics y Otros", "8_7_integraciones_api_con_magaya__dga__dynamics_y_otros.htm", [7]],
	"83": ["8.8 Penalidades a Vendedores por Cuentas Vencidas", "8_8_penalidades_a_vendedores_por_cuentas_vencidas.htm", [7]],
	"84": ["8.9 Parámetros Generales del Sistema", "8_9_parametros_generales_del_sistema.htm", [7]],
	"85": ["8.10 Control de Usuarios, Roles y Auditoría", "8_10_control_de_usuarios__roles_y_auditoria.htm", [7]],
	"86": ["9. Funciones Adicionales", "9__funciones_adicionales.htm", []],
	"87": ["9.1 Cálculo de Volumen y Peso", "9_1_calculo_de_volumen_y_peso.htm", [8]],
	"88": ["9.2 Uso de Perfiles de Cliente", "9_2_uso_de_perfiles_de_cliente.htm", [8]],
	"89": ["Paso a paso: Crear Perfil de Cliente", "paso_a_paso__crear_perfil_de_cliente.htm", [8,54]],
	"90": ["9.3 Incidencias de ventas", "9_3_incidencias_de_ventas.htm", [8]],
	"91": ["9.4 Contactos y Notificaciones", "9_4_contactos_y_notificaciones.htm", [8]],
	"92": ["9.5 Creación de Expedientes", "9_5_creacion_de_expedientes.htm", [8]],
	"93": ["9.6 Envío Automático de Notificaciones", "9_6_envio_automatico_de_notificaciones.htm", [8]],
	"94": ["9.7 Integración con Magaya, SIGA y SharePoint", "9_7_integracion_con_magaya__siga_y_sharepoint.htm", [8]],
	"95": ["9.8 Cálculo de Valor FOB y Flete", "9_8_calculo_de_valor_fob_y_flete.htm", [8]],
	"96": ["10. Glosario de Términos", "10__glosario_de_terminos.htm", []],
	"97": ["11. Preguntas Frecuentes (FAQs)", "11__preguntas_frecuentes__faqs_.htm", []]
};