DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0044"] = [
	{ "s": "DAMOS", "p": [10] },
	{ "s": "DAREMOS", "p": [10] },
	{ "s": "DATA", "p": [9, 4] },
	{ "s": "DATAVERSE", "p": [4, 5, 2, 9, 3, 10, 8] },
	{ "s": "DATOS", "p": [5, 4, 8, 9, 6, 11, 10, 3] },
	{ "s": "DATOS/IT", "p": [8] },
	{ "s": "DE", "p": [4, 6, 10, 7, 5, 9, 8, 3, 11] },
	{ "s": "DEBE", "p": [10, 11, 7, 6] },
	{ "s": "DEBERÁ", "p": [6, 5] },
	{ "s": "DEBERÁN", "p": [7] },
	{ "s": "DECISIONES", "p": [4] },
	{ "s": "DEFINICIÓN", "p": [6, 5] },
	{ "s": "DEFINIDOS", "p": [10, 6, 9, 4] },
	{ "s": "DEFINIR", "p": [10] },
	{ "s": "DEJAMOS", "p": [10] },
	{ "s": "DEL", "p": [10, 4, 9, 11, 6, 3, 8, 5, 7] },
	{ "s": "DENTRO", "p": [10, 4, 6] },
	{ "s": "DEPARTAMENTO", "p": [9] },
	{ "s": "DEPENDENCIAS", "p": [7] },
	{ "s": "DEPENDIENDO", "p": [4] },
	{ "s": "DESARROLLADAS", "p": [7, 5, 3] },
	{ "s": "DESARROLLADOS", "p": [5] },
	{ "s": "DESARROLLO", "p": [7, 8, 11, 6, 3] },
	{ "s": "DESASTRE", "p": [9, 3, 10] },
	{ "s": "DESASTRES", "p": [4, 10] },
	{ "s": "DESCARGAMOS", "p": [10] },
	{ "s": "DESCARGARÁ", "p": [10] },
	{ "s": "DESCRIBEN", "p": [4] },
	{ "s": "DESCRITO", "p": [10] },
	{ "s": "DESDE", "p": [10, 9, 7, 4] },
	{ "s": "DESEA", "p": [10] },
	{ "s": "DESEAMOS", "p": [10] },
	{ "s": "DESEMPEÑAR", "p": [6] },
	{ "s": "DESIGNADA", "p": [4] },
	{ "s": "DESPLIEGUE", "p": [7] },
	{ "s": "DESTINO", "p": [10] },
	{ "s": "DETALLA", "p": [9, 6] },
	{ "s": "DETALLADOS", "p": [10] },
	{ "s": "DETECTAR", "p": [6, 4] },
	{ "s": "DEV", "p": [7, 8] },
	{ "s": "DIAGRAMA", "p": [6] },
	{ "s": "DIARIAS", "p": [4] },
	{ "s": "DIARIO", "p": [9] },
	{ "s": "DIARIOS", "p": [4] },
	{ "s": "DIF", "p": [1] },
	{ "s": "DIFDR", "p": [10] },
	{ "s": "DIRECTA", "p": [8] },
	{ "s": "DIRECTAMENTE", "p": [10] },
	{ "s": "DIRIGIMOS", "p": [10] },
	{ "s": "DISASTER", "p": [2, 7, 1] },
	{ "s": "DISEÑADAS", "p": [5] },
	{ "s": "DISPONE", "p": [11] },
	{ "s": "DISPONEMOS", "p": [4] },
	{ "s": "DISPONIBILIDAD", "p": [8, 6, 4] },
	{ "s": "DISPONIBLE", "p": [10] },
	{ "s": "DISPONIBLES", "p": [10] },
	{ "s": "DISPUESTO", "p": [10] },
	{ "s": "DLSD", "p": [11, 10] },
	{ "s": "DOCUMENTA", "p": [11] },
	{ "s": "DOCUMENTADA", "p": [10] },
	{ "s": "DOCUMENTADOS", "p": [7] },
	{ "s": "DOCUMENTAR", "p": [5] },
	{ "s": "DOCUMENTO", "p": [11] },
	{ "s": "DOMINICANA", "p": [4] },
	{ "s": "DOMINIO", "p": [10] },
	{ "s": "DONDE", "p": [11] },
	{ "s": "DOS", "p": [9] },
	{ "s": "DRP", "p": [6, 11, 7, 5] },
	{ "s": "DURA", "p": [10] },
	{ "s": "DURANTE", "p": [6] },
	{ "s": "DÍAS", "p": [4] }
];