DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0043"] = [
	{ "s": "C", "p": [4] },
	{ "s": "CADA", "p": [6, 11, 10, 9, 7] },
	{ "s": "CAMBIAR", "p": [10] },
	{ "s": "CAMBIARLE", "p": [10] },
	{ "s": "CAMBIOS", "p": [11, 7, 6, 4] },
	{ "s": "CAPACIDAD", "p": [4, 10] },
	{ "s": "CAPACIDADES", "p": [10] },
	{ "s": "CARGAR", "p": [10] },
	{ "s": "CASO", "p": [4, 9, 5, 10, 7, 6, 11] },
	{ "s": "CASOS", "p": [7] },
	{ "s": "CENTER", "p": [10, 4] },
	{ "s": "CERTIFICARÁ", "p": [7] },
	{ "s": "CHECKLIST", "p": [10] },
	{ "s": "CHOOSE", "p": [10] },
	{ "s": "CIBERSEGURIDAD", "p": [8, 6, 9, 4] },
	{ "s": "CLARA", "p": [6] },
	{ "s": "CLASIFICACIÓN", "p": [8, 3] },
	{ "s": "CLAVE", "p": [11, 10, 6, 5, 4] },
	{ "s": "CLIC", "p": [10] },
	{ "s": "CLOUD", "p": [10] },
	{ "s": "COM", "p": [10] },
	{ "s": "COMO", "p": [10, 4, 5, 6, 11, 9] },
	{ "s": "COMPLEJIDAD", "p": [10] },
	{ "s": "COMPLETA", "p": [10, 9, 3] },
	{ "s": "COMPLETED", "p": [10] },
	{ "s": "COMPONENTE", "p": [5] },
	{ "s": "COMPONENTES", "p": [11] },
	{ "s": "COMPORTAMIENTO", "p": [4] },
	{ "s": "COMPRENDE", "p": [5] },
	{ "s": "COMPROMETAN", "p": [8] },
	{ "s": "COMPROMETIDO", "p": [4] },
	{ "s": "COMPUESTAS", "p": [5] },
	{ "s": "CON", "p": [10, 6, 7, 9, 5, 4, 11, 3] },
	{ "s": "CONCILIACIONES", "p": [6] },
	{ "s": "CONECTIVIDAD", "p": [8] },
	{ "s": "CONECTORES", "p": [5, 11, 6, 3] },
	{ "s": "CONEXIONES", "p": [6, 5, 4] },
	{ "s": "CONFIGURACIONES", "p": [7, 5] },
	{ "s": "CONFIGURACIÓN", "p": [10, 6] },
	{ "s": "CONFIRMAR", "p": [5] },
	{ "s": "CONFORME", "p": [6, 5] },
	{ "s": "CONNECTORS", "p": [5] },
	{ "s": "CONTAMOS", "p": [4] },
	{ "s": "CONTEMPLA", "p": [5] },
	{ "s": "CONTINGENCIA", "p": [11] },
	{ "s": "CONTINUA", "p": [11, 9, 4, 3] },
	{ "s": "CONTINUACIÓN", "p": [10, 4] },
	{ "s": "CONTINUAR", "p": [10] },
	{ "s": "CONTINUIDAD", "p": [4, 11, 10, 8, 6, 5] },
	{ "s": "CONTRIBUIRÁ", "p": [4] },
	{ "s": "CONTROL", "p": [7, 11, 4, 3] },
	{ "s": "CONTROLADA", "p": [6] },
	{ "s": "CONTROLES", "p": [6, 4] },
	{ "s": "CONVERTIR", "p": [10] },
	{ "s": "COORDINACIÓN", "p": [9, 7] },
	{ "s": "COORDINADA", "p": [6] },
	{ "s": "COORDINADOR", "p": [6] },
	{ "s": "COORDINAR", "p": [6, 7, 5] },
	{ "s": "COPIA", "p": [10] },
	{ "s": "COPIAS", "p": [6, 8, 4] },
	{ "s": "CORRECTA", "p": [6] },
	{ "s": "CORRECTAMENTE", "p": [10, 7] },
	{ "s": "CORRESPONDIENTES", "p": [10] },
	{ "s": "CORRUPCIÓN", "p": [9, 8, 5, 3] },
	{ "s": "CRITERIOS", "p": [10] },
	{ "s": "CRITICIDAD", "p": [8] },
	{ "s": "CRITICO", "p": [8] },
	{ "s": "CRM", "p": [10] },
	{ "s": "CRÍTICAS", "p": [5] },
	{ "s": "CRÍTICOS", "p": [8, 11, 10, 6, 5, 4, 3] },
	{ "s": "CUAL", "p": [10, 4] },
	{ "s": "CUALES", "p": [4, 7, 5] },
	{ "s": "CUENTA", "p": [9, 6, 4] },
	{ "s": "CULTURA", "p": [11] },
	{ "s": "CUMPLIMIENTO", "p": [5, 4] },
	{ "s": "CUSTOM", "p": [5] },
	{ "s": "CUYA", "p": [9] }
];