DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0053"] = [
	{ "s": "SANDBOX", "p": [10, 7] },
	{ "s": "SE", "p": [10, 9, 4, 11, 7] },
	{ "s": "SEA", "p": [10] },
	{ "s": "SECCIÓN", "p": [10, 9, 8, 6] },
	{ "s": "SECUNDARIA", "p": [9] },
	{ "s": "SECUNDARIO", "p": [10, 11, 9] },
	{ "s": "SEGMENTACIÓN", "p": [6] },
	{ "s": "SEGUIMIENTOS", "p": [10] },
	{ "s": "SEGUNDA", "p": [11] },
	{ "s": "SEGUNDO", "p": [10] },
	{ "s": "SEGUNDOS", "p": [4] },
	{ "s": "SEGURIDAD", "p": [6, 4, 8] },
	{ "s": "SEGUROS", "p": [7] },
	{ "s": "SEGÚN", "p": [10, 7] },
	{ "s": "SELECCIONADOS", "p": [10] },
	{ "s": "SELECCIONAR", "p": [10] },
	{ "s": "SELECTIVA", "p": [10, 3] },
	{ "s": "SER", "p": [4] },
	{ "s": "SERVICIO", "p": [4, 8] },
	{ "s": "SERVICIOS", "p": [10, 6, 5, 9] },
	{ "s": "SHARED", "p": [10] },
	{ "s": "SHAREPOINT", "p": [10, 6] },
	{ "s": "SI", "p": [10, 9, 6] },
	{ "s": "SIGNIFICATIVA", "p": [4] },
	{ "s": "SIGUIENDO", "p": [6] },
	{ "s": "SIGUIENTE", "p": [10, 6] },
	{ "s": "SIGUIENTES", "p": [4] },
	{ "s": "SIMILAR", "p": [10] },
	{ "s": "SIMULACROS", "p": [11] },
	{ "s": "SIMULANDO", "p": [10] },
	{ "s": "SIN", "p": [4] },
	{ "s": "SINCRONIZACIÓN", "p": [5] },
	{ "s": "SINCRONIZADOS", "p": [6] },
	{ "s": "SINO", "p": [7] },
	{ "s": "SISTEMA", "p": [10, 4, 8, 6, 3, 11, 9] },
	{ "s": "SISTEMAS", "p": [7, 6, 5] },
	{ "s": "SITES", "p": [10] },
	{ "s": "SITIO", "p": [10] },
	{ "s": "SLA", "p": [4] },
	{ "s": "SOBRE", "p": [11, 10, 5, 4] },
	{ "s": "SOLO", "p": [10] },
	{ "s": "SOLUCIONES", "p": [7, 5] },
	{ "s": "SOLUCIÓN", "p": [11, 7, 4] },
	{ "s": "SON", "p": [9, 7] },
	{ "s": "SOSPECHOSAS", "p": [6] },
	{ "s": "SQL", "p": [9] },
	{ "s": "STANDARD", "p": [5] },
	{ "s": "STATUS", "p": [10] },
	{ "s": "SU", "p": [8, 5, 7] },
	{ "s": "SUBIDA", "p": [10] },
	{ "s": "SUBIR", "p": [10] },
	{ "s": "SUFRA", "p": [10] },
	{ "s": "SUPERVISAR", "p": [6] },
	{ "s": "SUPERVISIÓN", "p": [6, 4] },
	{ "s": "SUS", "p": [6, 11, 4] }
];