DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0049"] = [
	{ "s": "IDENTIFICA", "p": [8] },
	{ "s": "IDENTIFICADOS", "p": [9] },
	{ "s": "IDENTIFICAR", "p": [5, 4] },
	{ "s": "IGUAL", "p": [10] },
	{ "s": "ILUSTRA", "p": [10] },
	{ "s": "IMAGEN", "p": [10] },
	{ "s": "IMPACTO", "p": [8, 11, 6, 5] },
	{ "s": "IMPLEMENTACIÓN", "p": [4, 3] },
	{ "s": "IMPLEMENTAN", "p": [7] },
	{ "s": "IMPLEMENTAR", "p": [6, 5] },
	{ "s": "IMPLEMENTARÁN", "p": [4] },
	{ "s": "IMPORT", "p": [10] },
	{ "s": "IMPORTAR", "p": [10] },
	{ "s": "IMPOSIBILIDAD", "p": [8] },
	{ "s": "IMPULSADA", "p": [11] },
	{ "s": "INACTIVIDAD", "p": [4, 3] },
	{ "s": "INACTIVO", "p": [4] },
	{ "s": "INCIDENTE", "p": [4, 7, 11, 10, 9, 6] },
	{ "s": "INCIDENTES", "p": [6, 5, 4] },
	{ "s": "INCLUIRÁ", "p": [4] },
	{ "s": "INCLUYE", "p": [5] },
	{ "s": "INCLUYEN", "p": [10, 6] },
	{ "s": "INCLUYENDO", "p": [4] },
	{ "s": "INCONSISTENCIAS", "p": [7] },
	{ "s": "INESPERADOS", "p": [11] },
	{ "s": "INFORMACIÓN", "p": [6, 10, 9, 4] },
	{ "s": "INFRAESTRUCTURA", "p": [6, 8, 9, 4] },
	{ "s": "INFRAESTRUCTURA/IT", "p": [8] },
	{ "s": "INGRESAMOS", "p": [10] },
	{ "s": "INICIAL", "p": [10] },
	{ "s": "INICIAR", "p": [10] },
	{ "s": "INICIO", "p": [10] },
	{ "s": "INMEDIATAS", "p": [6] },
	{ "s": "INTEGRACIONES", "p": [6, 10] },
	{ "s": "INTEGRACIÓN", "p": [6, 5] },
	{ "s": "INTEGRAL", "p": [4] },
	{ "s": "INTEGRAR", "p": [5] },
	{ "s": "INTEGRIDAD", "p": [10, 4, 7, 6] },
	{ "s": "INTERACCIÓN", "p": [6] },
	{ "s": "INTERNET", "p": [8] },
	{ "s": "INTERNO", "p": [9] },
	{ "s": "INTERNOS", "p": [10, 9] },
	{ "s": "INTERRUPCION", "p": [8] },
	{ "s": "INTERRUPCIONES", "p": [11] },
	{ "s": "INTERRUPCIÓN", "p": [10, 9, 8, 4] },
	{ "s": "INUSUALES", "p": [6] },
	{ "s": "INVENTARIO", "p": [5] },
	{ "s": "INVOLUCRADOS", "p": [6] },
	{ "s": "IR", "p": [10] },
	{ "s": "IRLANDA", "p": [9] },
	{ "s": "IT", "p": [8] }
];