DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0046"] = [
	{ "s": "FACILITANDO", "p": [6] },
	{ "s": "FACTURACIÓN", "p": [6] },
	{ "s": "FALLA", "p": [10, 9, 7, 3] },
	{ "s": "FALLAS", "p": [8, 4] },
	{ "s": "FALLOS", "p": [5, 6, 4] },
	{ "s": "FECHA", "p": [10] },
	{ "s": "FILE", "p": [10] },
	{ "s": "FILTROS", "p": [10] },
	{ "s": "FIN", "p": [11] },
	{ "s": "FINAL", "p": [7] },
	{ "s": "FINALMENTE", "p": [7] },
	{ "s": "FINANCIERAS", "p": [6] },
	{ "s": "FINANCIEROS", "p": [6] },
	{ "s": "FINISH", "p": [10] },
	{ "s": "FLUJO", "p": [7, 4] },
	{ "s": "FLUJOS", "p": [5, 11, 10, 8, 7, 6, 3] },
	{ "s": "FOMENTAR", "p": [11] },
	{ "s": "FORMA", "p": [6] },
	{ "s": "FORMS", "p": [10] },
	{ "s": "FORTALECER", "p": [4] },
	{ "s": "FORTALECIENDO", "p": [11] },
	{ "s": "FROM", "p": [10] },
	{ "s": "FUE", "p": [10] },
	{ "s": "FUERA", "p": [4] },
	{ "s": "FUERON", "p": [10] },
	{ "s": "FUNCIONAL", "p": [8] },
	{ "s": "FUNCIONALES", "p": [6, 7, 5] },
	{ "s": "FUNCIONALIDAD", "p": [5] },
	{ "s": "FUNCIONALIDADES", "p": [10] },
	{ "s": "FUNCIONAMIENTO", "p": [6] },
	{ "s": "FUNCIONES", "p": [6] },
	{ "s": "FUNDAMENTALES", "p": [7] }
];