DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u004d"] = [
	{ "s": "MAGNITUD", "p": [10] },
	{ "s": "MANERA", "p": [10] },
	{ "s": "MANTENER", "p": [4, 11, 10, 7, 6, 5] },
	{ "s": "MANTIENE", "p": [9] },
	{ "s": "MANUAL", "p": [10, 6] },
	{ "s": "MARCO", "p": [4, 6, 3] },
	{ "s": "MAYORES", "p": [5] },
	{ "s": "MECANISMOS", "p": [11, 10, 9, 8, 7, 5, 4] },
	{ "s": "MEDIA", "p": [8] },
	{ "s": "MEDIANTE", "p": [11, 9, 4] },
	{ "s": "MEDIDA", "p": [10, 4] },
	{ "s": "MEDIDAS", "p": [4] },
	{ "s": "MEJORA", "p": [11, 3] },
	{ "s": "MEJORES", "p": [11] },
	{ "s": "MENCIONADO", "p": [10] },
	{ "s": "MENCIONADOS", "p": [10] },
	{ "s": "MENSUAL", "p": [4] },
	{ "s": "MESES", "p": [10] },
	{ "s": "MFA", "p": [6, 4] },
	{ "s": "MICROSOFT", "p": [9, 4, 10, 5, 3] },
	{ "s": "MIGRACIÓN", "p": [5] },
	{ "s": "MIGRARSE", "p": [10] },
	{ "s": "MINIMIZACIÓN", "p": [4, 3] },
	{ "s": "MINIMIZANDO", "p": [10, 5] },
	{ "s": "MINIMIZAR", "p": [6, 4] },
	{ "s": "MINUTOS", "p": [10, 4] },
	{ "s": "MISMO", "p": [10] },
	{ "s": "MITIGACIÓN", "p": [9] },
	{ "s": "MOMENTO", "p": [10] },
	{ "s": "MONITOREAR", "p": [8] },
	{ "s": "MONITOREO", "p": [6, 4, 8, 3] },
	{ "s": "MORTEM", "p": [11] },
	{ "s": "MOSTRADA", "p": [10] },
	{ "s": "MOSTRADOS", "p": [10] },
	{ "s": "MOSTRAMOS", "p": [10] },
	{ "s": "MOSTRAR", "p": [10] },
	{ "s": "MUESTRA", "p": [10] },
	{ "s": "MULTIFACTOR", "p": [6, 4] },
	{ "s": "MÁS", "p": [10, 9] },
	{ "s": "MÁXIMO", "p": [4] },
	{ "s": "MÉTODOS", "p": [9] },
	{ "s": "MÉTRICAS", "p": [10] },
	{ "s": "MÍNIMO", "p": [6] },
	{ "s": "MÓDULOS", "p": [8] }
];