DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0050"] = [
	{ "s": "PAGOS", "p": [6] },
	{ "s": "PANTALLA", "p": [10] },
	{ "s": "PARA", "p": [4, 10, 6, 5, 7, 9, 8, 11] },
	{ "s": "PARCIAL", "p": [9, 5] },
	{ "s": "PARTE", "p": [10, 5] },
	{ "s": "PARTIR", "p": [7] },
	{ "s": "PARÁMETROS", "p": [10] },
	{ "s": "PASO", "p": [10] },
	{ "s": "PASOS", "p": [10] },
	{ "s": "PAÍSES", "p": [9] },
	{ "s": "PERDER", "p": [4] },
	{ "s": "PERDIDA", "p": [8] },
	{ "s": "PERIÓDICA", "p": [8, 5, 4] },
	{ "s": "PERIÓDICAS", "p": [11] },
	{ "s": "PERMANECER", "p": [4] },
	{ "s": "PERMISOS", "p": [8, 6] },
	{ "s": "PERMITE", "p": [10, 4] },
	{ "s": "PERMITEN", "p": [10] },
	{ "s": "PERMITIENDO", "p": [11, 10, 7, 4] },
	{ "s": "PERSONA", "p": [6] },
	{ "s": "PERSONALIZADAS", "p": [5, 3] },
	{ "s": "PERSONALIZADOS", "p": [5] },
	{ "s": "PLAFORM", "p": [10] },
	{ "s": "PLAN", "p": [6, 5, 2, 10, 7, 4, 1] },
	{ "s": "PLATFORM", "p": [6, 5, 4] },
	{ "s": "PLAZO", "p": [10] },
	{ "s": "PODEMOS", "p": [10] },
	{ "s": "POINT", "p": [4] },
	{ "s": "POLÍTICAS", "p": [4] },
	{ "s": "POR", "p": [5, 4, 7, 11, 10, 9] },
	{ "s": "PORTAL", "p": [10] },
	{ "s": "POSIBLES", "p": [4] },
	{ "s": "POST", "p": [11, 7, 5] },
	{ "s": "POST-INCIDENTE", "p": [7] },
	{ "s": "POST-RESTAURACIÓN", "p": [5] },
	{ "s": "POSTERIOR", "p": [10] },
	{ "s": "POSTURA", "p": [4] },
	{ "s": "POWER", "p": [6, 5, 4, 3, 2, 8, 10] },
	{ "s": "POWERPLATFORM", "p": [10] },
	{ "s": "POWERS", "p": [4] },
	{ "s": "PRD", "p": [10] },
	{ "s": "PRECEDIDA", "p": [7] },
	{ "s": "PRECISA", "p": [6] },
	{ "s": "PREPARACIÓN", "p": [11] },
	{ "s": "PREVENIR", "p": [4] },
	{ "s": "PREVENTIVA", "p": [10] },
	{ "s": "PREVIAMENTE", "p": [10] },
	{ "s": "PREVIAS", "p": [7] },
	{ "s": "PRINCIPAL", "p": [10, 11, 8, 5] },
	{ "s": "PRINCIPALES", "p": [9] },
	{ "s": "PRINCIPIO", "p": [6] },
	{ "s": "PRIVILEGIO", "p": [6] },
	{ "s": "PROACTIVAMENTE", "p": [4] },
	{ "s": "PROBLEMAS", "p": [4] },
	{ "s": "PROCEDERÁ", "p": [9] },
	{ "s": "PROCEDIMIENTO", "p": [10] },
	{ "s": "PROCEDIMIENTOS", "p": [10, 6, 11, 9, 5, 4] },
	{ "s": "PROCESO", "p": [10, 6, 11, 8, 3] },
	{ "s": "PROCESOS", "p": [6, 5, 11, 9, 7, 4] },
	{ "s": "PRODUCCIÓN", "p": [7, 10, 11, 9, 4, 3] },
	{ "s": "PRODUCTIVO", "p": [10] },
	{ "s": "PROGRAMACIÓN", "p": [7, 5, 4] },
	{ "s": "PROGRAMADAS", "p": [5] },
	{ "s": "PROGRAMADOR", "p": [8, 6, 5] },
	{ "s": "PROGRAMADOR/EQUIPO", "p": [8] },
	{ "s": "PROGRESS", "p": [10] },
	{ "s": "PROMOCIÓN", "p": [7] },
	{ "s": "PROMOVER", "p": [10, 7] },
	{ "s": "PROPORCIONADOS", "p": [4] },
	{ "s": "PROPÓSITO", "p": [4] },
	{ "s": "PROTECCIÓN", "p": [4] },
	{ "s": "PROTEGIDOS", "p": [5] },
	{ "s": "PROTOCOLOS", "p": [6] },
	{ "s": "PROVENIENTE", "p": [10] },
	{ "s": "PRUEBA", "p": [7, 11, 10, 4, 3] },
	{ "s": "PRUEBAS", "p": [10, 6, 9, 8, 7, 5, 3] },
	{ "s": "PRÁCTICA", "p": [11] },
	{ "s": "PUEDA", "p": [10] },
	{ "s": "PUEDAN", "p": [11] },
	{ "s": "PUEDE", "p": [4, 10, 9] },
	{ "s": "PUNTO", "p": [10, 4] },
	{ "s": "PUNTOS", "p": [10, 6] },
	{ "s": "PÉRDIDA", "p": [9, 5, 4, 8, 3] }
];