DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0052"] = [
	{ "s": "RANGO", "p": [4] },
	{ "s": "RASTREO", "p": [7] },
	{ "s": "RAZONABLE", "p": [9] },
	{ "s": "REALES", "p": [10] },
	{ "s": "REALISTAS", "p": [10] },
	{ "s": "REALIZA", "p": [7, 4] },
	{ "s": "REALIZACIÓN", "p": [8] },
	{ "s": "REALIZADAS", "p": [7] },
	{ "s": "REALIZAMOS", "p": [10] },
	{ "s": "REALIZAN", "p": [10] },
	{ "s": "REALIZAR", "p": [10] },
	{ "s": "REALIZARÁ", "p": [5] },
	{ "s": "REASON", "p": [10] },
	{ "s": "RECIENTE", "p": [10, 9] },
	{ "s": "RECONFIGURACIÓN", "p": [5] },
	{ "s": "RECOVERY", "p": [2, 4, 7, 1] },
	{ "s": "RECUPERACIÓN", "p": [6, 4, 9, 3, 10, 8, 5, 11, 7] },
	{ "s": "RECUPERAR", "p": [10] },
	{ "s": "REDES", "p": [6] },
	{ "s": "REDIRECCIONARÁ", "p": [9] },
	{ "s": "REDUCIDO", "p": [10] },
	{ "s": "REFERENCIA", "p": [4] },
	{ "s": "REGIONAL", "p": [9, 3] },
	{ "s": "REGIONES", "p": [9, 4] },
	{ "s": "REGISTRO", "p": [11, 10, 9, 3] },
	{ "s": "REGISTROS", "p": [10, 9, 6, 5, 4, 3] },
	{ "s": "REGIÓN", "p": [9] },
	{ "s": "REIMPORTACIÓN", "p": [5] },
	{ "s": "REIMPORTAN", "p": [9] },
	{ "s": "REINCORPORACIÓN", "p": [9] },
	{ "s": "RELACIONADOS", "p": [6, 5] },
	{ "s": "RELACIONES", "p": [5] },
	{ "s": "RENDIMIENTO", "p": [4] },
	{ "s": "REPLICA", "p": [9] },
	{ "s": "REPLICACIÓN", "p": [9] },
	{ "s": "REPORTAR", "p": [7] },
	{ "s": "REPORTES", "p": [11] },
	{ "s": "REPOSITORIOS", "p": [7] },
	{ "s": "REPRESENTA", "p": [10] },
	{ "s": "REPÚBLICA", "p": [4] },
	{ "s": "REQUERIDOS", "p": [7] },
	{ "s": "RESILIENCIA", "p": [6, 4] },
	{ "s": "RESOLVERSE", "p": [9] },
	{ "s": "RESPALDAN", "p": [4] },
	{ "s": "RESPALDAR", "p": [5] },
	{ "s": "RESPALDO", "p": [10, 9, 5, 11, 8, 4] },
	{ "s": "RESPALDOS", "p": [4, 9, 7] },
	{ "s": "RESPONDER", "p": [4] },
	{ "s": "RESPONSABILIDAD", "p": [9] },
	{ "s": "RESPONSABILIDADES", "p": [6, 4, 3] },
	{ "s": "RESPONSABLE", "p": [9, 6, 7, 5, 8] },
	{ "s": "RESPONSABLES", "p": [6, 3, 11, 9, 8, 7, 4] },
	{ "s": "RESPUESTA", "p": [6, 10, 11] },
	{ "s": "RESTABLECE", "p": [9] },
	{ "s": "RESTABLECER", "p": [6] },
	{ "s": "RESTABLECIMIENTO", "p": [6] },
	{ "s": "RESTAURACIÓN", "p": [10, 3, 5, 9, 6, 8, 7, 4] },
	{ "s": "RESTAURADAS", "p": [6] },
	{ "s": "RESTAURADO", "p": [10] },
	{ "s": "RESTAURADOS", "p": [5] },
	{ "s": "RESTAURAMOS", "p": [10] },
	{ "s": "RESTAURAR", "p": [10, 9] },
	{ "s": "RESTORE", "p": [10] },
	{ "s": "RESTRICCIÓN", "p": [4] },
	{ "s": "RESULTADO", "p": [10] },
	{ "s": "RETENCIÓN", "p": [4] },
	{ "s": "REVISAR", "p": [6] },
	{ "s": "REVISIONES", "p": [11] },
	{ "s": "REVISIÓN", "p": [11, 4] },
	{ "s": "RIEGO", "p": [8] },
	{ "s": "ROLES", "p": [6, 11, 8, 4, 3] },
	{ "s": "RPO", "p": [4, 5] },
	{ "s": "RTO", "p": [4, 10, 5] }
];