DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0052"] = [
	{ "s": "READONLYUSERMAPPINGFILECONTAINERURI", "p": [8, 9] },
	{ "s": "REAL", "p": [11, 8] },
	{ "s": "REALICE", "p": [10] },
	{ "s": "REALIZACIÓN", "p": [8] },
	{ "s": "REALIZADO", "p": [9, 5] },
	{ "s": "REALIZADOS", "p": [9] },
	{ "s": "REALIZAMOS", "p": [5] },
	{ "s": "REALIZAR", "p": [5, 13, 12, 11, 10] },
	{ "s": "REALIZARLE", "p": [13] },
	{ "s": "RECHAZAR", "p": [8] },
	{ "s": "RECIENTES", "p": [6] },
	{ "s": "RECOMENDADO", "p": [8] },
	{ "s": "RECUPERAR", "p": [6, 3] },
	{ "s": "RECURSO", "p": [11] },
	{ "s": "RECURSOS", "p": [11] },
	{ "s": "RED", "p": [11] },
	{ "s": "REEMPLAZAR", "p": [10] },
	{ "s": "REFIERE", "p": [7] },
	{ "s": "REGIONES", "p": [11] },
	{ "s": "REGISTRO", "p": [11] },
	{ "s": "REGISTROS", "p": [7] },
	{ "s": "REJECTED", "p": [9] },
	{ "s": "REMOVE", "p": [9] },
	{ "s": "REPOSITORY", "p": [9] },
	{ "s": "REPÚBLICA", "p": [11] },
	{ "s": "REQUERIR", "p": [11] },
	{ "s": "REQUEST", "p": [9] },
	{ "s": "REQUESTID", "p": [9] },
	{ "s": "REQUIERE", "p": [11, 8] },
	{ "s": "RESERVADO", "p": [7] },
	{ "s": "RESOURCE", "p": [9] },
	{ "s": "RESTABLECIDO", "p": [6] },
	{ "s": "RESTAURACIÓN", "p": [5, 6] },
	{ "s": "RESTAURAR", "p": [5, 3] },
	{ "s": "RESTORE", "p": [5] },
	{ "s": "RESTRICTIVA", "p": [11] },
	{ "s": "RESTRINGIRSE", "p": [7] },
	{ "s": "RESULTADOS", "p": [13] },
	{ "s": "RESUMEN", "p": [11] },
	{ "s": "RETENCIÓN", "p": [12, 3] },
	{ "s": "RETORNADO", "p": [4] },
	{ "s": "RETORNAR", "p": [4, 3] },
	{ "s": "RETURN", "p": [8] },
	{ "s": "REVISAR", "p": [8] },
	{ "s": "REVISE", "p": [11] },
	{ "s": "REÚNE", "p": [11] },
	{ "s": "RIESGO", "p": [11] },
	{ "s": "ROL", "p": [7, 3, 11] },
	{ "s": "ROLA", "p": [10] },
	{ "s": "ROLES", "p": [7, 10, 3, 11] },
	{ "s": "RUN", "p": [9] },
	{ "s": "RUTA", "p": [8] },
	{ "s": "RWL", "p": [8] },
	{ "s": "RWL&SCID", "p": [8] },
	{ "s": "RÁPIDAMENTE", "p": [11] }
];