DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0041"] = [
	{ "s": "A", "p": [11, 7, 8, 4, 10, 5, 9, 3, 13, 12, 6] },
	{ "s": "A316", "p": [8] },
	{ "s": "A6392FE7", "p": [8] },
	{ "s": "A6392FE7-8F0C-456C-A929-A79CB55DEB21", "p": [8] },
	{ "s": "A79CB55DEB21", "p": [8] },
	{ "s": "A7D3", "p": [8] },
	{ "s": "A929", "p": [8] },
	{ "s": "ABAJO", "p": [11, 8] },
	{ "s": "ABC4752BF346", "p": [8] },
	{ "s": "ABOVE", "p": [8] },
	{ "s": "ABRA", "p": [10, 9] },
	{ "s": "ABRIRÁ", "p": [10] },
	{ "s": "ACCEDER", "p": [7, 11, 10, 8] },
	{ "s": "ACCESIBLE", "p": [10] },
	{ "s": "ACCESO", "p": [11, 7, 3, 8] },
	{ "s": "ACCESOS", "p": [13, 10, 3] },
	{ "s": "ACCESS", "p": [11, 9] },
	{ "s": "ACCIDENTALMENTE", "p": [10] },
	{ "s": "ACCIONES", "p": [7, 11] },
	{ "s": "ACCIÓN", "p": [11] },
	{ "s": "ACCOUNT", "p": [9] },
	{ "s": "ACDC", "p": [12] },
	{ "s": "ACTIVADO", "p": [10] },
	{ "s": "ACTIVAR", "p": [11] },
	{ "s": "ACTIVOS", "p": [8] },
	{ "s": "ACTOR", "p": [11] },
	{ "s": "ACTUALICE", "p": [8] },
	{ "s": "ACTUALMENTE", "p": [8] },
	{ "s": "ADD", "p": [9, 8, 10] },
	{ "s": "ADD-POWERAPPSACCOUNT", "p": [8, 9, 10] },
	{ "s": "ADDRESS", "p": [9] },
	{ "s": "ADECUADA", "p": [8] },
	{ "s": "ADMIN", "p": [9, 10, 11, 6, 5] },
	{ "s": "ADMINISTRACIÓN", "p": [10, 11, 7, 5, 3, 9, 6, 4] },
	{ "s": "ADMINISTRADO", "p": [10] },
	{ "s": "ADMINISTRADOR", "p": [8, 10, 11, 9, 12, 6, 5, 4, 3] },
	{ "s": "ADMINISTRADORES", "p": [11, 8, 10, 9] },
	{ "s": "ADMINISTRADOS", "p": [10, 3, 11] },
	{ "s": "ADMINISTRAR", "p": [7, 10, 11, 5] },
	{ "s": "ADMINISTRATION", "p": [9, 8, 10] },
	{ "s": "ADMINISTRATIVOS", "p": [11] },
	{ "s": "ADMINISTRATORS", "p": [9] },
	{ "s": "ADMINPOWERAPPENVIRONMENT", "p": [12] },
	{ "s": "ADMINPOWERAPPENVIRONMENTBACKUPRETENTIONPERIOD", "p": [12] },
	{ "s": "ADMINPOWERAPPENVIRONMENTGOVERNANCECONFIGURATION", "p": [10] },
	{ "s": "ADMITE", "p": [10] },
	{ "s": "AFECTADOS", "p": [10] },
	{ "s": "AFECTEN", "p": [10] },
	{ "s": "AGREGAR", "p": [7, 3] },
	{ "s": "AHORA", "p": [11] },
	{ "s": "AISLADO", "p": [10] },
	{ "s": "AJUSTE", "p": [7] },
	{ "s": "AL", "p": [11, 7, 8, 10, 9, 5] },
	{ "s": "ALERTAS", "p": [11] },
	{ "s": "ALGUNO", "p": [12, 11] },
	{ "s": "ALGÚN", "p": [9] },
	{ "s": "ALL", "p": [9] },
	{ "s": "ALLÁ", "p": [11] },
	{ "s": "ALMACENAMIENTO", "p": [8] },
	{ "s": "AND", "p": [9] },
	{ "s": "ANOTAR", "p": [8] },
	{ "s": "ANTE", "p": [12] },
	{ "s": "ANTERIOR", "p": [8] },
	{ "s": "ANTERIORES", "p": [13] },
	{ "s": "ANTERIORMENTE", "p": [8] },
	{ "s": "ANTES", "p": [10, 8] },
	{ "s": "APAGAR", "p": [10] },
	{ "s": "APARECE", "p": [7, 10] },
	{ "s": "API", "p": [11, 10] },
	{ "s": "APLICACIONES", "p": [11] },
	{ "s": "APLICACIÓN", "p": [11, 7] },
	{ "s": "APLICADAS", "p": [11, 3] },
	{ "s": "APLICADO", "p": [11] },
	{ "s": "APLICAR", "p": [11, 10] },
	{ "s": "APLICARLE", "p": [11] },
	{ "s": "APPLY", "p": [9] },
	{ "s": "APPROVAL", "p": [9] },
	{ "s": "APPROVE", "p": [9, 8] },
	{ "s": "APPROVED", "p": [9] },
	{ "s": "APPROVING", "p": [9] },
	{ "s": "APROBACIÓN", "p": [8] },
	{ "s": "APROBADA", "p": [11, 8] },
	{ "s": "APROBAR", "p": [8] },
	{ "s": "AQUI", "p": [8] },
	{ "s": "AQUÍ", "p": [8, 11, 10, 7, 6, 4] },
	{ "s": "ARCHIVO", "p": [8, 9, 3] },
	{ "s": "AS", "p": [9] },
	{ "s": "ASEGURARSE", "p": [10] },
	{ "s": "ASEGURÁNDOSE", "p": [8] },
	{ "s": "ASEGÚRESE", "p": [10, 9, 8] },
	{ "s": "ASIGNACIÓN", "p": [8] },
	{ "s": "ASOCIADOS", "p": [7] },
	{ "s": "ASÍ", "p": [11, 10] },
	{ "s": "AUDIT", "p": [13] },
	{ "s": "AUDITAR", "p": [13] },
	{ "s": "AUDITORIA", "p": [13, 3] },
	{ "s": "AUTENTICACIÓN", "p": [11, 10] },
	{ "s": "AUTENTICARSE", "p": [8] },
	{ "s": "AUTOMÁTICAMENTE", "p": [7] },
	{ "s": "AUTORIDAD", "p": [7] },
	{ "s": "AYUDAR", "p": [11] },
	{ "s": "AYUDE", "p": [8] },
	{ "s": "AZ", "p": [9] },
	{ "s": "AZSTORAGEBLOBCONTENT", "p": [9, 8] },
	{ "s": "AZSTORAGECONTEXT", "p": [9, 8] },
	{ "s": "AZURE", "p": [9, 11, 8] }
];