DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0053"] = [
	{ "s": "S", "p": [8] },
	{ "s": "SABER", "p": [12] },
	{ "s": "SALIDA", "p": [8] },
	{ "s": "SANDBOX", "p": [4, 3] },
	{ "s": "SAS", "p": [9, 8] },
	{ "s": "SASTOKEN", "p": [9, 8] },
	{ "s": "SASURI", "p": [8, 9] },
	{ "s": "SATISFACTORIA", "p": [10, 8, 6] },
	{ "s": "SATISFACTORIAMENTE", "p": [4] },
	{ "s": "SAVE", "p": [9] },
	{ "s": "SCID", "p": [8] },
	{ "s": "SCRIPT", "p": [10, 9, 8] },
	{ "s": "SE", "p": [8, 7, 11, 10, 4, 12, 9, 6] },
	{ "s": "SEA", "p": [11] },
	{ "s": "SECCIONES", "p": [8] },
	{ "s": "SECUNDARIAS", "p": [7] },
	{ "s": "SEE", "p": [9] },
	{ "s": "SEGUIR", "p": [8] },
	{ "s": "SEGUNDO", "p": [10] },
	{ "s": "SEGURIDAD", "p": [7, 11, 3, 5, 12, 10] },
	{ "s": "SEGÚN", "p": [10] },
	{ "s": "SELECCIONA", "p": [5] },
	{ "s": "SELECCIONADO", "p": [7, 6] },
	{ "s": "SELECCIONAMOS", "p": [5, 13, 11, 4, 9, 6] },
	{ "s": "SELECCIONE", "p": [7, 10, 11, 6, 5] },
	{ "s": "SELECCIONEENTORNOS", "p": [7] },
	{ "s": "SELECCIONES", "p": [4] },
	{ "s": "SELECIONAMOS", "p": [5] },
	{ "s": "SELECT", "p": [9] },
	{ "s": "SENSITIVE", "p": [9] },
	{ "s": "SEPARADO", "p": [12] },
	{ "s": "SEPARATE", "p": [9] },
	{ "s": "SEQUENTIALLY", "p": [9] },
	{ "s": "SER", "p": [12, 9, 11, 10] },
	{ "s": "SERVICIO", "p": [11] },
	{ "s": "SERÁ", "p": [8] },
	{ "s": "SESIÓN", "p": [11, 10, 8, 7, 6, 9, 5, 4] },
	{ "s": "SET", "p": [10, 12, 8] },
	{ "s": "SET-ADMINPOWERAPPENVIRONMENTBACKUPRETENTIONPERIOD", "p": [12] },
	{ "s": "SET-ADMINPOWERAPPENVIRONMENTGOVERNANCECONFIGURATION", "p": [10] },
	{ "s": "SET-AZSTORAGEBLOBCONTENT", "p": [8] },
	{ "s": "SETTINGS", "p": [13] },
	{ "s": "SEÑALES", "p": [11] },
	{ "s": "SI", "p": [11, 10, 9, 13] },
	{ "s": "SIETE", "p": [11] },
	{ "s": "SIG", "p": [8] },
	{ "s": "SIGA", "p": [9] },
	{ "s": "SIGN", "p": [9] },
	{ "s": "SIGUIENTE", "p": [8, 12, 11, 13, 10, 6, 4] },
	{ "s": "SIGUIENTES", "p": [11, 8, 12, 13] },
	{ "s": "SIMPLE", "p": [11, 8] },
	{ "s": "SIN", "p": [10, 12, 11] },
	{ "s": "SINOPSIS", "p": [11] },
	{ "s": "SISTEMA", "p": [10, 5, 11, 8] },
	{ "s": "SKE", "p": [8] },
	{ "s": "SKOID", "p": [8] },
	{ "s": "SKS", "p": [8] },
	{ "s": "SKT", "p": [8] },
	{ "s": "SKTID", "p": [8] },
	{ "s": "SKV", "p": [8] },
	{ "s": "SOBRE", "p": [7, 11, 8] },
	{ "s": "SOLICITA", "p": [7] },
	{ "s": "SOLICITUD", "p": [8] },
	{ "s": "SOLICITUDES", "p": [8] },
	{ "s": "SOLO", "p": [10, 11, 9] },
	{ "s": "SON", "p": [11] },
	{ "s": "SOURCE", "p": [9] },
	{ "s": "SOURCETENANT", "p": [9] },
	{ "s": "SP", "p": [8] },
	{ "s": "SPLIT", "p": [9, 8] },
	{ "s": "SPR", "p": [8] },
	{ "s": "SR", "p": [8] },
	{ "s": "ST", "p": [8] },
	{ "s": "STATUS", "p": [9] },
	{ "s": "STEP", "p": [9] },
	{ "s": "STORAGE", "p": [9] },
	{ "s": "STORAGEACCOUNTNAME", "p": [9, 8] },
	{ "s": "STORAGECONTEXT", "p": [9, 8] },
	{ "s": "SU", "p": [11, 7, 12, 9, 8, 4] },
	{ "s": "SUBIR", "p": [8] },
	{ "s": "SUBIRLO", "p": [9] },
	{ "s": "SUBMIT", "p": [9] },
	{ "s": "SUBMITMIGRATIONREQUEST", "p": [9, 8] },
	{ "s": "SUBORDINADAS", "p": [7] },
	{ "s": "SUBSTRING", "p": [8] },
	{ "s": "SUELE", "p": [7] },
	{ "s": "SUGERENCIAS", "p": [11] },
	{ "s": "SUPERIOR", "p": [7] },
	{ "s": "SUPERVISAR", "p": [8] },
	{ "s": "SUPERVISIÓN", "p": [11] },
	{ "s": "SUS", "p": [11, 10, 7] },
	{ "s": "SUSCRIPCIÓN", "p": [10] },
	{ "s": "SUSTITUYENDO", "p": [8] },
	{ "s": "SV", "p": [8] },
	{ "s": "SYSTEM", "p": [8] },
	{ "s": "SYSTEM.URI", "p": [8] },
	{ "s": "SÍMBOLO", "p": [10] }
];