DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0049"] = [
	{ "s": "ICONO", "p": [7] },
	{ "s": "ID", "p": [11, 10, 8, 12, 9] },
	{ "s": "IDENTIDAD", "p": [11] },
	{ "s": "IDENTIDADES", "p": [11] },
	{ "s": "IDENTIFICADOR", "p": [8] },
	{ "s": "IDENTIFICAR", "p": [11] },
	{ "s": "IF", "p": [11, 8] },
	{ "s": "IF-THEN", "p": [11] },
	{ "s": "IGUAL", "p": [13] },
	{ "s": "IMAGEN", "p": [12, 8, 13, 10, 7] },
	{ "s": "IMPLEMENTACIÓN", "p": [11, 3] },
	{ "s": "IMPLICA", "p": [8] },
	{ "s": "IMPORTANTE", "p": [9] },
	{ "s": "IN", "p": [9] },
	{ "s": "INCLUYE", "p": [11] },
	{ "s": "INCLUYEN", "p": [11] },
	{ "s": "INDEPENDIENTEMENTE", "p": [7] },
	{ "s": "INDICA", "p": [8, 4] },
	{ "s": "INFORMACIÓN", "p": [11, 7, 8] },
	{ "s": "INFORME", "p": [9] },
	{ "s": "INGRESE", "p": [7] },
	{ "s": "INICIADO", "p": [4] },
	{ "s": "INICIAMOS", "p": [8] },
	{ "s": "INICIAR", "p": [13, 8, 11, 10] },
	{ "s": "INICIE", "p": [7, 10, 8, 6, 9, 5, 4] },
	{ "s": "INICIO", "p": [11] },
	{ "s": "INICIOS", "p": [11] },
	{ "s": "INQUILINO", "p": [8, 9] },
	{ "s": "INSTALACIÓN", "p": [8, 3] },
	{ "s": "INSTALAR", "p": [10, 8] },
	{ "s": "INSTALE", "p": [8] },
	{ "s": "INSTALL", "p": [9, 10, 8] },
	{ "s": "INSTALL-MODULE", "p": [9, 10, 8] },
	{ "s": "INSTRUCCIONES", "p": [11] },
	{ "s": "INTEGRACIÓN", "p": [11] },
	{ "s": "INTENSIDAD", "p": [11] },
	{ "s": "INTENTA", "p": [10] },
	{ "s": "INTENTAN", "p": [11] },
	{ "s": "INTENTEN", "p": [11] },
	{ "s": "INTERACTUAR", "p": [8] },
	{ "s": "INTERVALOS", "p": [11] },
	{ "s": "INTO", "p": [9] },
	{ "s": "INTRODUCCIÓN", "p": [8] },
	{ "s": "IP", "p": [11] },
	{ "s": "ISE", "p": [8] }
];