DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0043"] = [
	{ "s": "C", "p": [8, 9, 5] },
	{ "s": "C&SP", "p": [8] },
	{ "s": "C:\\DOWNLOADS\\FAILED", "p": [9] },
	{ "s": "C:\\MIGRACION\\USERMAPPING.CSV", "p": [8] },
	{ "s": "CABO", "p": [11] },
	{ "s": "CALCULADO", "p": [11] },
	{ "s": "CAMBIADO", "p": [12, 4] },
	{ "s": "CAMBIANDO", "p": [10, 8] },
	{ "s": "CAMBIAR", "p": [12] },
	{ "s": "CAMBIARÁ", "p": [4] },
	{ "s": "CAMBIE", "p": [10] },
	{ "s": "CAMBIO", "p": [12, 11, 4] },
	{ "s": "CAMBIOS", "p": [10] },
	{ "s": "CAMPOS", "p": [11] },
	{ "s": "CANTIDAD", "p": [13] },
	{ "s": "CAPACIDAD", "p": [11] },
	{ "s": "CAPACIDADES", "p": [8] },
	{ "s": "CAPACITAR", "p": [11] },
	{ "s": "CARGAR", "p": [8] },
	{ "s": "CARGUE", "p": [8] },
	{ "s": "CASE", "p": [9] },
	{ "s": "CASE-SENSITIVE", "p": [9] },
	{ "s": "CENTER", "p": [11] },
	{ "s": "CENTRO", "p": [10, 7, 11, 9, 6, 5, 4] },
	{ "s": "CERO", "p": [11] },
	{ "s": "CHARACTER", "p": [9] },
	{ "s": "CHECK", "p": [9] },
	{ "s": "CLICK", "p": [9] },
	{ "s": "CLIENTE", "p": [11] },
	{ "s": "CMDLET", "p": [9] },
	{ "s": "COBERTURA", "p": [11] },
	{ "s": "COLOCA", "p": [8] },
	{ "s": "COLOCAR", "p": [8] },
	{ "s": "COLUMN", "p": [9] },
	{ "s": "COLUMNS", "p": [9] },
	{ "s": "COM", "p": [10, 9, 11, 6, 5] },
	{ "s": "COMANDO", "p": [8, 9, 12, 10] },
	{ "s": "COMANDOS", "p": [8, 7, 12] },
	{ "s": "COMANDÓ", "p": [8] },
	{ "s": "COMENZAR", "p": [9, 8] },
	{ "s": "COMILLAS", "p": [8] },
	{ "s": "COMMAND", "p": [8] },
	{ "s": "COMMANDS", "p": [9] },
	{ "s": "COMO", "p": [11, 10, 8, 7, 12, 6] },
	{ "s": "COMPARTIDO", "p": [8] },
	{ "s": "COMPARTIDOS", "p": [7] },
	{ "s": "COMPATIBLE", "p": [11] },
	{ "s": "COMPLETADO", "p": [8] },
	{ "s": "COMPLETAMENTE", "p": [8] },
	{ "s": "COMPLETAMOS", "p": [11] },
	{ "s": "COMPLETAR", "p": [8, 11, 6] },
	{ "s": "COMPLETE", "p": [8] },
	{ "s": "COMPLETOS", "p": [11] },
	{ "s": "COMPORTAMIENTO", "p": [11] },
	{ "s": "COMPORTAMIENTOS", "p": [11] },
	{ "s": "COMPROBADOS", "p": [8] },
	{ "s": "COMPROBAMOS", "p": [11] },
	{ "s": "COMPROBAR", "p": [8] },
	{ "s": "COMUNES", "p": [11, 3] },
	{ "s": "CON", "p": [11, 8, 7, 10, 12, 9, 4, 5] },
	{ "s": "CONCEDER", "p": [11] },
	{ "s": "CONCRETAS", "p": [11] },
	{ "s": "CONCRETO", "p": [11] },
	{ "s": "CONCRETOS", "p": [11] },
	{ "s": "CONCUERDEN", "p": [8] },
	{ "s": "CONDICIONAL", "p": [11, 3] },
	{ "s": "CONDICIONES", "p": [11] },
	{ "s": "CONDICIÓN", "p": [11] },
	{ "s": "CONDITIONAL", "p": [11] },
	{ "s": "CONFIANZA", "p": [11] },
	{ "s": "CONFIGURACIÓN", "p": [7, 12, 13, 11, 3] },
	{ "s": "CONFIGURAR", "p": [10] },
	{ "s": "CONFIRMA", "p": [6] },
	{ "s": "CONFIRMACIÓN", "p": [8, 5] },
	{ "s": "CONFIRMADO", "p": [4] },
	{ "s": "CONFIRMAMOS", "p": [4, 12, 10, 6] },
	{ "s": "CONFIRMAR", "p": [5, 12, 10] },
	{ "s": "CONFIRMAREMOS", "p": [6] },
	{ "s": "CONFIRME", "p": [7] },
	{ "s": "CONSISTE", "p": [8] },
	{ "s": "CONTAINER", "p": [8, 9] },
	{ "s": "CONTAINERNAME", "p": [9] },
	{ "s": "CONTAMOS", "p": [12] },
	{ "s": "CONTENGAN", "p": [8] },
	{ "s": "CONTEXT", "p": [9, 8] },
	{ "s": "CONTEXTO", "p": [8] },
	{ "s": "CONTINUACIÓN", "p": [10, 7, 9, 8] },
	{ "s": "CONTINUAR", "p": [9, 8] },
	{ "s": "CONTRASEÑA", "p": [11] },
	{ "s": "CONTROL", "p": [11] },
	{ "s": "CONTROLADO", "p": [11] },
	{ "s": "CONVERSIÓN", "p": [4] },
	{ "s": "CONVERTIR", "p": [4, 10, 8, 3] },
	{ "s": "CONVIERTE", "p": [10] },
	{ "s": "COPIA", "p": [5] },
	{ "s": "COPIAS", "p": [12, 5] },
	{ "s": "CORE", "p": [8] },
	{ "s": "CORRECTAMENTE", "p": [9] },
	{ "s": "CORRECTIVAS", "p": [11] },
	{ "s": "CORRECTO", "p": [9] },
	{ "s": "CORREGIR", "p": [11] },
	{ "s": "CORREGIRLO", "p": [9] },
	{ "s": "CORREO", "p": [7] },
	{ "s": "CORRER", "p": [8] },
	{ "s": "CORRESPONDA", "p": [10] },
	{ "s": "CORRIENDO", "p": [6] },
	{ "s": "COUTRIES", "p": [11] },
	{ "s": "CREACIÓN", "p": [11, 8] },
	{ "s": "CREADA", "p": [11] },
	{ "s": "CREAR", "p": [11, 8, 5] },
	{ "s": "CREAREMOS", "p": [11] },
	{ "s": "CREATE", "p": [9, 11] },
	{ "s": "CREDENCIALES", "p": [10, 8, 5, 4] },
	{ "s": "CRUCIAL", "p": [8] },
	{ "s": "CRUD", "p": [7] },
	{ "s": "CRUD-TRANSPORTE", "p": [7] },
	{ "s": "CSV", "p": [9, 8] },
	{ "s": "CUAL", "p": [8, 4] },
	{ "s": "CUANDO", "p": [10, 11] },
	{ "s": "CUENTA", "p": [11, 10] },
	{ "s": "CULMINE", "p": [6] },
	{ "s": "CÓDIGO", "p": [10] },
	{ "s": "CÓMO", "p": [12, 10] }
];