DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0041"] = [
	{ "s": "A", "p": [8, 7, 4, 6, 3] },
	{ "s": "ABRE", "p": [8] },
	{ "s": "ACCEDER", "p": [8] },
	{ "s": "ACCESOS", "p": [8] },
	{ "s": "ACCIONES", "p": [8] },
	{ "s": "ACCOUNT", "p": [5] },
	{ "s": "ACTIVIDAD", "p": [8] },
	{ "s": "ACTIVITY", "p": [5] },
	{ "s": "ACTUALMENTE", "p": [4] },
	{ "s": "ACTÚA", "p": [7] },
	{ "s": "ACTÚAN", "p": [8] },
	{ "s": "ACUMULAR", "p": [8] },
	{ "s": "ADICIONALES", "p": [4] },
	{ "s": "ADJUNTOS", "p": [8, 4] },
	{ "s": "ADMIN", "p": [8] },
	{ "s": "ADMIN.POWERPLATFORM.MICROSOFT.COM", "p": [8] },
	{ "s": "ADMINISTRA", "p": [4] },
	{ "s": "ADMINISTRACIONES", "p": [5] },
	{ "s": "ADMINISTRACIÓN", "p": [8, 3] },
	{ "s": "ADMINISTRAR", "p": [8, 4] },
	{ "s": "ADUANA", "p": [5] },
	{ "s": "ADUANALES", "p": [5] },
	{ "s": "ADUANAS", "p": [5, 7] },
	{ "s": "ADVERTENCIAS", "p": [8] },
	{ "s": "AERONAVES", "p": [5] },
	{ "s": "AFTER", "p": [8] },
	{ "s": "AGENTE", "p": [7] },
	{ "s": "AL", "p": [8] },
	{ "s": "ALLÍ", "p": [8] },
	{ "s": "ALMACENA", "p": [4] },
	{ "s": "ALMACENADA", "p": [4] },
	{ "s": "ALMACENAMIENTO", "p": [8, 4] },
	{ "s": "ALMACENAR", "p": [4] },
	{ "s": "ALOJADA", "p": [8] },
	{ "s": "AND", "p": [4] },
	{ "s": "ANTERIORMENTE", "p": [8] },
	{ "s": "ANTIGUAS", "p": [8] },
	{ "s": "ANTIGUO", "p": [8] },
	{ "s": "ANTIGUOS", "p": [8] },
	{ "s": "APARECERÁ", "p": [8] },
	{ "s": "APLICA", "p": [8] },
	{ "s": "APLICACIONES", "p": [8, 4] },
	{ "s": "APLICACIÓN", "p": [8] },
	{ "s": "APPOIMENT", "p": [5] },
	{ "s": "APPS", "p": [8] },
	{ "s": "AQUÍ", "p": [8] },
	{ "s": "ARCHIVO", "p": [4] },
	{ "s": "ARCHIVOS", "p": [8, 4] },
	{ "s": "ASEGÚRATE", "p": [8] },
	{ "s": "ASIGNA", "p": [8] },
	{ "s": "ASINCRÓNICAS", "p": [8] },
	{ "s": "ASINCRÓNICO", "p": [8] },
	{ "s": "ASINCRÓNICOS", "p": [8, 3] },
	{ "s": "ASISTENTE", "p": [8] },
	{ "s": "ASOCIADA", "p": [8] },
	{ "s": "ASOCIADO", "p": [7, 5] },
	{ "s": "ASOCIADOS", "p": [5] },
	{ "s": "ASYNCHRONOUS", "p": [8] },
	{ "s": "ATRIBUTOS", "p": [6, 3] },
	{ "s": "ATTACHMENT", "p": [5] },
	{ "s": "ATTACHMENTS", "p": [8] },
	{ "s": "AUDIT", "p": [8] },
	{ "s": "AUDITORIA", "p": [5] },
	{ "s": "AUDITORÍA", "p": [8] },
	{ "s": "AUDITORÍAS", "p": [8] },
	{ "s": "AUNQUE", "p": [8, 6] },
	{ "s": "AUTO", "p": [6, 7] },
	{ "s": "AUTO-REFERENCIA", "p": [6] },
	{ "s": "AUTO-RELACIONES", "p": [7] },
	{ "s": "AUTOMATE", "p": [8] },
	{ "s": "AUTOMATIZACIÓN", "p": [8, 4] },
	{ "s": "AVANZADA", "p": [8] },
	{ "s": "AYUDA", "p": [5] },
	{ "s": "AÑO", "p": [8] }
];