DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0052"] = [
	{ "s": "RAZONES", "p": [5] },
	{ "s": "RAZÓN", "p": [8] },
	{ "s": "REAL", "p": [4] },
	{ "s": "REALIZAN", "p": [8] },
	{ "s": "REALIZAR", "p": [8] },
	{ "s": "REANUDARSE", "p": [8] },
	{ "s": "REASON", "p": [8] },
	{ "s": "RECEPTIVA", "p": [8] },
	{ "s": "RECHAZO", "p": [5] },
	{ "s": "RECIBIR", "p": [8] },
	{ "s": "RECIBOS", "p": [5] },
	{ "s": "RECUPERAR", "p": [4] },
	{ "s": "RECURRENTE", "p": [8] },
	{ "s": "RECURSIVAS", "p": [7] },
	{ "s": "RECURSOS", "p": [8] },
	{ "s": "REDUCE", "p": [8] },
	{ "s": "REDUCIR", "p": [8] },
	{ "s": "REEMBOLSO", "p": [5] },
	{ "s": "REFERENCIA", "p": [6, 7] },
	{ "s": "REGISTRO", "p": [8] },
	{ "s": "REGISTROS", "p": [8, 4] },
	{ "s": "REGISTROS/LOGS", "p": [8] },
	{ "s": "REGULAR", "p": [8] },
	{ "s": "REINTENTAR", "p": [8] },
	{ "s": "RELACIONADAS", "p": [7] },
	{ "s": "RELACIONADOS", "p": [8] },
	{ "s": "RELACIONES", "p": [7, 4, 3] },
	{ "s": "RELACIÓN", "p": [7, 2, 6] },
	{ "s": "RENDIMIENTO", "p": [8] },
	{ "s": "REPORTES", "p": [8] },
	{ "s": "REPRESENTA", "p": [7, 4] },
	{ "s": "REPRESENTACIÓN", "p": [4] },
	{ "s": "REQUIEREN", "p": [8] },
	{ "s": "REQUISITOS", "p": [8] },
	{ "s": "RESERVAS", "p": [5] },
	{ "s": "RESUMEN", "p": [8] },
	{ "s": "RETENCIÓN", "p": [8] },
	{ "s": "REVISA", "p": [8] },
	{ "s": "REVISAR", "p": [8] },
	{ "s": "ROBUSTA", "p": [4] },
	{ "s": "ROLES", "p": [7] },
	{ "s": "RUN", "p": [8] },
	{ "s": "RUTAS", "p": [8] },
	{ "s": "RÁPIDAS", "p": [8] }
];