DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u0054"] = [
	{ "s": "TABLA", "p": [6, 8, 7, 4] },
	{ "s": "TABLAS", "p": [4, 8] },
	{ "s": "TABLE", "p": [8, 6] },
	{ "s": "TABS", "p": [8] },
	{ "s": "TAMBIÉN", "p": [8, 7] },
	{ "s": "TANTO", "p": [8] },
	{ "s": "TAREAS", "p": [8] },
	{ "s": "TARIFA", "p": [5] },
	{ "s": "TASA", "p": [5] },
	{ "s": "TASK", "p": [5] },
	{ "s": "TE", "p": [8] },
	{ "s": "TEAM", "p": [5] },
	{ "s": "TEMPORALES", "p": [8] },
	{ "s": "TEN", "p": [8] },
	{ "s": "TEXTO", "p": [4] },
	{ "s": "THIS", "p": [8] },
	{ "s": "TI", "p": [8] },
	{ "s": "TIEMPO", "p": [8] },
	{ "s": "TIENE", "p": [7] },
	{ "s": "TIPO", "p": [8, 5, 7, 4] },
	{ "s": "TIPOS", "p": [8, 4] },
	{ "s": "TITLE", "p": [1] },
	{ "s": "TODA", "p": [4] },
	{ "s": "TODAS", "p": [8] },
	{ "s": "TRABAJO", "p": [8] },
	{ "s": "TRABAJO/PROCESOS", "p": [8] },
	{ "s": "TRABAJOS", "p": [8, 3] },
	{ "s": "TRADICIONAL", "p": [4] },
	{ "s": "TRANSACCIONES", "p": [5] },
	{ "s": "TRANSPORTE", "p": [5] },
	{ "s": "TRANSPORTISTA", "p": [7] },
	{ "s": "TRATADOS", "p": [5] },
	{ "s": "TRES", "p": [4] },
	{ "s": "TU", "p": [8] },
	{ "s": "TYPE", "p": [8] },
	{ "s": "TÍPICO", "p": [7] }
];