DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex["\u004d"] = [
	{ "s": "MAESTRO", "p": [5] },
	{ "s": "MANAGEMENT", "p": [8] },
	{ "s": "MANERAS", "p": [8] },
	{ "s": "MANIPULAR", "p": [4] },
	{ "s": "MANTENER", "p": [8] },
	{ "s": "MANTENIMIENTO", "p": [5] },
	{ "s": "MANUALMENTE", "p": [8] },
	{ "s": "MARÍTIMO", "p": [5] },
	{ "s": "MASIVA", "p": [8, 3] },
	{ "s": "MASIVAS", "p": [8] },
	{ "s": "MEJORA", "p": [8] },
	{ "s": "MEJORES", "p": [8, 3] },
	{ "s": "MENSAJES", "p": [8] },
	{ "s": "MENSUAL", "p": [8] },
	{ "s": "MESES", "p": [8] },
	{ "s": "MICROSOFT", "p": [8, 4] },
	{ "s": "MIENTRAS", "p": [8, 4] },
	{ "s": "MINIMIZAR", "p": [8] },
	{ "s": "MISMA", "p": [7] },
	{ "s": "MODELAR", "p": [4] },
	{ "s": "MODELO", "p": [2, 7] },
	{ "s": "MODELOS", "p": [8] },
	{ "s": "MONITOREAR", "p": [8] },
	{ "s": "MONITOREO", "p": [8, 3] },
	{ "s": "MOSTRAR", "p": [8] },
	{ "s": "MOTOR", "p": [8] },
	{ "s": "MUCHAS", "p": [8, 7] },
	{ "s": "MUCHOS", "p": [7] },
	{ "s": "MUNDO", "p": [4] },
	{ "s": "MUY", "p": [8] },
	{ "s": "MÁS", "p": [8] },
	{ "s": "MÓDULO", "p": [8] },
	{ "s": "MÚLTIPLES", "p": [8, 7] }
];