DR_EXPLAIN = DR_EXPLAIN || {};
DR_EXPLAIN.searchIndex = DR_EXPLAIN.searchIndex || {};
DR_EXPLAIN.searchIndex.prefixes = [
	{ "fileName": "0xu0030.js", "first": "00", "last": "06" },
	{ "fileName": "0xu0031.js", "first": "1", "last": "18" },
	{ "fileName": "0xu0032.js", "first": "2", "last": "25" },
	{ "fileName": "0xu0033.js", "first": "3", "last": "365" },
	{ "fileName": "0xu0034.js", "first": "4", "last": "4500" },
	{ "fileName": "0xu0035.js", "first": "5", "last": "58.25" },
	{ "fileName": "0xu0036.js", "first": "6", "last": "6.5" },
	{ "fileName": "0xu0037.js", "first": "7", "last": "7.6" },
	{ "fileName": "0xu0038.js", "first": "8", "last": "840" },
	{ "fileName": "0xu0039.js", "first": "9", "last": "9.8" },
	{ "fileName": "0xu0041.js", "first": "A", "last": "AÚN" },
	{ "fileName": "0xu0042.js", "first": "B", "last": "BÚSQUEDAS" },
	{ "fileName": "0xu0043.js", "first": "C", "last": "CÚBICOS" },
	{ "fileName": "0xu0044.js", "first": "D", "last": "DÓNDE" },
	{ "fileName": "0xu0045.js", "first": "E", "last": "EXW" },
	{ "fileName": "0xu0046.js", "first": "FACILITA", "last": "FÍSICO" },
	{ "fileName": "0xu0047.js", "first": "GANANCIA", "last": "GUÍA" },
	{ "fileName": "0xu0048.js", "first": "HA", "last": "HUBO" },
	{ "fileName": "0xu0049.js", "first": "ID", "last": "ITINERARIO" },
	{ "fileName": "0xu004a.js", "first": "JUN2025", "last": "JUSTIFICANDO" },
	{ "fileName": "0xu004b.js", "first": "KG", "last": "KPIS" },
	{ "fileName": "0xu004c.js", "first": "L", "last": "LÍNEAS" },
	{ "fileName": "0xu004d.js", "first": "MAERSK", "last": "MÚLTIPLES" },
	{ "fileName": "0xu004e.js", "first": "NACIONAL", "last": "NÚMEROS" },
	{ "fileName": "0xu004f.js", "first": "O", "last": "OTROS" },
	{ "fileName": "0xu0050.js", "first": "PACKING", "last": "PÓLIZAS" },
	{ "fileName": "0xu0051.js", "first": "QA", "last": "QUÍMICOS" },
	{ "fileName": "0xu0052.js", "first": "RANGO", "last": "RÍO" },
	{ "fileName": "0xu0053.js", "first": "SABER", "last": "SÍMBOLOS" },
	{ "fileName": "0xu0054.js", "first": "TAL", "last": "TÚ" },
	{ "fileName": "0xu0055.js", "first": "U", "last": "UTILIZARÁ" },
	{ "fileName": "0xu0056.js", "first": "VA", "last": "VÍNCULO" },
	{ "fileName": "0xu0057.js", "first": "WORD", "last": "WORD" },
	{ "fileName": "0xu0058.js", "first": "X", "last": "XML" },
	{ "fileName": "0xu0059.js", "first": "Y", "last": "YA" },
	{ "fileName": "0xu005a.js", "first": "ZARPA", "last": "ZONAS" },
	{ "fileName": "0xu00c1.js", "first": "ÁREA", "last": "ÁREA" },
	{ "fileName": "0xu00cd.js", "first": "ÍCONO", "last": "ÍTEMS" },
	{ "fileName": "0xu00d3.js", "first": "Ó", "last": "ÓRDENES" },
	{ "fileName": "0xu00da.js", "first": "ÚNICA", "last": "ÚTILES" },
	{ "fileName": "0xufe0f.js", "first": "️", "last": "️" }
];